"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Invite={athleteUserId:string;email:string;name:string;createdAt:string|null};

export default function PendingAthleteInvitesPage(){
 const[invites,setInvites]=useState<Invite[]>([]),[loading,setLoading]=useState(true),[working,setWorking]=useState<string|null>(null),[message,setMessage]=useState("");
 async function load(){setLoading(true);const supabase=createSupabaseBrowserClient();const{data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth/coach";return;}const response=await fetch("/api/athlete-invitations/manage",{headers:{Authorization:`Bearer ${session.access_token}`}});const result=await response.json();if(!response.ok){setMessage(result.error??"Unable to load invitations.");setInvites([]);}else setInvites(result.invites??[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function act(invite:Invite,action:"resend"|"cancel"){if(action==="cancel"&&!confirm(`Cancel ${invite.name}'s invitation? This will remove the unactivated athlete workspace and any workout templates so the email can be invited again.`))return;setWorking(invite.athleteUserId);setMessage("");const supabase=createSupabaseBrowserClient();const{data:{session}}=await supabase.auth.getSession();if(!session){location.href="/auth/coach";return;}const response=await fetch("/api/athlete-invitations/manage",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,athleteUserId:invite.athleteUserId})});const result=await response.json();if(!response.ok)setMessage(result.error??"Unable to manage invitation.");else{setMessage(action==="resend"?`Fresh activation email sent to ${invite.email}.`:`Invitation cancelled. ${invite.email} can now be invited again.`);await load();}setWorking(null);}
 return <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10"><header><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Coach</p><h1 className="mt-2 text-3xl font-bold">Pending Athlete Invites</h1><p className="mt-2 text-zinc-400">Resend activation links or remove accounts that have never been activated. Activated athletes are not shown here.</p></header>{message&&<p className="rounded-xl border border-zinc-800 p-4 text-sm">{message}</p>}{loading?<p className="text-zinc-400">Beep boop... checking invitation status.</p>:invites.length===0?<section className="rounded-2xl border border-zinc-800 p-6"><p className="font-semibold">No pending athlete invitations.</p><p className="mt-2 text-sm text-zinc-400">Everyone currently linked has activated their account, or there are no invited athletes yet.</p></section>:<section className="flex flex-col gap-3">{invites.map(invite=><article key={invite.athleteUserId} className="rounded-2xl border border-zinc-800 p-5"><div><p className="font-bold">{invite.name}</p><p className="mt-1 text-sm text-zinc-400">{invite.email}</p>{invite.createdAt&&<p className="mt-1 text-xs text-zinc-600">Invited {new Date(invite.createdAt).toLocaleString()}</p>}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Link href={`/coach/athletes/${invite.athleteUserId}`} className="rounded-lg border border-zinc-700 px-3 py-2 text-center text-sm font-semibold">Open Athlete</Link><button disabled={working===invite.athleteUserId} onClick={()=>act(invite,"resend")} className="rounded-lg border border-zinc-700 px-3 py-2 text-sm font-semibold disabled:opacity-50">Resend Invite</button><button disabled={working===invite.athleteUserId} onClick={()=>act(invite,"cancel")} className="rounded-lg border border-red-900 px-3 py-2 text-sm font-semibold text-red-300 disabled:opacity-50">Cancel Invite</button></div></article>)}</section>}<div className="grid gap-2 sm:grid-cols-2"><Link href="/coach/invite-athlete" className="phat-accent-bg rounded-lg px-5 py-3 text-center font-semibold">Invite Athlete</Link><Link href="/coach" className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Back to Coach Dashboard</Link></div></main>;
}
