"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Session={id:string;completed_at:string};
type WorkoutScore={workout_session_id:string;score:number|null};
type VolumeSet={weight:number;reps:number;set_type:string};
type ExerciseVolume={workout_session_id:string;sets:VolumeSet[]};
type WeekPoint={key:string;label:string;start:Date;end:Date;score:number|null;completed:number;scored:number;volume:number};
function mondayOf(date:Date){const copy=new Date(date),day=copy.getDay(),diff=day===0?6:day-1;copy.setDate(copy.getDate()-diff);copy.setHours(0,0,0,0);return copy;}
function key(date:Date){const d=mondayOf(date);const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function formatVolume(value:number){return value>=1000000?`${(value/1000000).toFixed(value>=10000000?1:2)}M`:value>=1000?`${(value/1000).toFixed(value>=100000?0:1)}k`:Math.round(value).toLocaleString();}
function trendMessage(change:number|null,latest:WeekPoint|null,currentWeekInProgress:boolean){if(!latest)return"Beep boop. I need a little more comparable training data before my trend sensors can make a call.";if(currentWeekInProgress)return`Week in progress. Your current scored-workout average is ${latest.score}%. PHATBOT will make the week-over-week call after this training week closes.`;if(change===null)return"First scored week detected. Baseline locked in. Now we build.";if(change>5)return`Gains detected. Your weekly performance score climbed ${change} points. Keep feeding the machine.`;if(change>0)return`Positive signal detected. You moved up ${change} point${change===1?"":"s"} from your prior scored week.`;if(change===0)return"Strength signal holding steady. Matching prior performance is still useful data. Next mission: create separation.";if(change>=-5)return`Small dip detected: ${Math.abs(change)} point${Math.abs(change)===1?"":"s"}. No robot panic. Recovery, execution, and the next workout matter.`;return`Performance dipped ${Math.abs(change)} points from the prior scored week. PHATBOT recommends reviewing the recent workouts and attacking the next one with a plan.`;}
export default function ProgressPage(){const [sessions,setSessions]=useState<Session[]>([]),[workoutScores,setWorkoutScores]=useState<WorkoutScore[]>([]),[exerciseVolumes,setExerciseVolumes]=useState<ExerciseVolume[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
useEffect(()=>{const supabase=createSupabaseBrowserClient();async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return;}const cutoff=new Date();cutoff.setDate(cutoff.getDate()-70);cutoff.setHours(0,0,0,0);const {data:sessionData,error:sessionError}=await supabase.from("workout_sessions").select("id,completed_at").eq("athlete_user_id",user.id).eq("status","completed").gte("completed_at",cutoff.toISOString()).order("completed_at",{ascending:true});if(sessionError){setMessage(sessionError.message);setLoading(false);return;}const completed=(sessionData??[]) as Session[];const ids=completed.map(s=>s.id);let scores:WorkoutScore[]=[];let volumes:ExerciseVolume[]=[];if(ids.length){const [{data:scoreData,error:scoreError},{data:volumeData,error:volumeError}]=await Promise.all([supabase.from("workout_scores").select("workout_session_id,score").eq("athlete_user_id",user.id).in("workout_session_id",ids),supabase.from("exercise_sessions").select("workout_session_id,sets(weight,reps,set_type)").in("workout_session_id",ids)]);if(scoreError||volumeError)setMessage(scoreError?.message??volumeError?.message??"");if(!scoreError)scores=(scoreData??[]) as WorkoutScore[];if(!volumeError)volumes=(volumeData??[]) as ExerciseVolume[];}setSessions(completed);setWorkoutScores(scores);setExerciseVolumes(volumes);setLoading(false);}load();},[]);
const weeks=useMemo<WeekPoint[]>(()=>{const current=mondayOf(new Date()),scoreBySession=new Map(workoutScores.map(w=>[w.workout_session_id,w.score==null?null:Number(w.score)*100])),volumeBySession=new Map<string,number>();for(const ex of exerciseVolumes){const exerciseVolume=(ex.sets??[]).filter(s=>["working","top","backoff"].includes(s.set_type)).reduce((sum,s)=>sum+(Number(s.weight)||0)*(Number(s.reps)||0),0);volumeBySession.set(ex.workout_session_id,(volumeBySession.get(ex.workout_session_id)??0)+exerciseVolume);}return Array.from({length:8},(_,i)=>{const start=new Date(current);start.setDate(start.getDate()-7*(7-i));const end=new Date(start);end.setDate(end.getDate()+6);end.setHours(23,59,59,999);const weekKey=key(start),weekSessions=sessions.filter(s=>key(new Date(s.completed_at))===weekKey),scores=weekSessions.map(s=>scoreBySession.get(s.id)).filter((v):v is number=>v!==undefined&&v!==null),score=scores.length?Math.round(scores.reduce((sum,v)=>sum+v,0)/scores.length):null,volume=weekSessions.reduce((sum,s)=>sum+(volumeBySession.get(s.id)??0),0);return{key:weekKey,label:`${start.getMonth()+1}/${start.getDate()}`,start,end,score,completed:weekSessions.length,scored:scores.length,volume};});},[sessions,workoutScores,exerciseVolumes]);
const currentWeek=weeks.at(-1)??null,currentWeekInProgress=!!currentWeek&&new Date()<currentWeek.end,scored=weeks.filter(w=>w.score!==null),latest=scored.at(-1)??null,prior=scored.length>1?scored[scored.length-2]:null,latestIsCurrent=!!latest&&!!currentWeek&&latest.key===currentWeek.key&&currentWeekInProgress,change=!latestIsCurrent&&latest&&prior?latest.score!-prior.score!:null,total=weeks.reduce((n,w)=>n+w.completed,0),maxVolume=Math.max(...weeks.map(w=>w.volume),1);const volumeWeeks=weeks.filter(w=>w.volume>0),latestVolume=volumeWeeks.at(-1)??null,priorVolume=volumeWeeks.length>1?volumeWeeks[volumeWeeks.length-2]:null,latestVolumeIsCurrent=!!latestVolume&&!!currentWeek&&latestVolume.key===currentWeek.key&&currentWeekInProgress,volumeChange=!latestVolumeIsCurrent&&latestVolume&&priorVolume&&priorVolume.volume>0?((latestVolume.volume-priorVolume.volume)/priorVolume.volume)*100:null;
if(loading)return <main className="mx-auto min-h-screen max-w-3xl px-6 py-12 text-zinc-300">Beep boop... loading training progress.</main>;
return <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10"><header><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Progress Center</p><h1 className="mt-2 text-3xl font-bold">Your training intelligence</h1><p className="mt-2 text-zinc-400">Reports, trends, PRs, and performance history all live here.</p></header>{message&&<p className="rounded-xl border border-zinc-800 p-4 text-sm">{message}</p>}
<section className="grid gap-3 sm:grid-cols-2"><Link href="/reports" className="rounded-2xl border border-[#ff0032]/50 bg-[#ff0032]/5 p-5 transition hover:border-[#ff0032]"><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Reports</p><h2 className="mt-2 text-xl font-bold">Performance Reports →</h2><p className="mt-2 text-sm text-zinc-400">Review this week, lifetime, or any custom date range.</p></Link><Link href="/progress/trends" className="rounded-2xl border border-zinc-700 p-5 transition hover:border-[#ff0032]"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-500">Trends</p><h2 className="mt-2 text-xl font-bold">Explore Trends <span className="phat-accent">→</span></h2><p className="mt-2 text-sm text-zinc-400">Choose workout trends or exercise trends from one place.</p></Link></section>
<section className="phat-signal rounded-2xl border p-5"><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">PHATBOT Trend Scan</p><p className="mt-3 text-lg font-semibold leading-relaxed">{trendMessage(change,latest,latestIsCurrent)}</p></section><section className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">{latestIsCurrent?"Current week score":"Latest scored week"}</p><p className="mt-2 text-3xl font-bold">{!latest?"N/A":`${latest.score}%`}</p>{latestIsCurrent&&<p className="mt-2 text-xs font-semibold uppercase tracking-wider text-zinc-600">Week in progress</p>}</div><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">Week-over-week</p><p className={`mt-2 text-3xl font-bold ${change!==null&&change>0?"phat-accent":""}`}>{latestIsCurrent?"Pending":change===null?"N/A":`${change>0?"+":""}${change} pts`}</p>{latestIsCurrent&&<p className="mt-2 text-xs text-zinc-600">Available when the week closes.</p>}</div><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">8-week workouts</p><p className="mt-2 text-3xl font-bold">{total}</p></div></section>
<section className="rounded-2xl border border-zinc-800 p-5"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">8-week score telemetry</h2><p className="mt-1 text-sm text-zinc-500">Includes live and imported historical workouts. Weekly scores average all comparable workout scores in each week.</p></div><span className="text-xs text-zinc-600">0–100%</span></div><div className="mt-8 flex h-64 items-end gap-2 sm:gap-4">{weeks.map(w=>{const h=w.score===null?4:Math.max(8,w.score),isCurrent=!!currentWeek&&w.key===currentWeek.key&&currentWeekInProgress;return <div key={w.key} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-semibold text-zinc-300">{w.score===null?"—":w.score}</span><div className="flex h-48 w-full items-end rounded-lg bg-zinc-900 p-1"><div className="w-full rounded-md bg-[#ff0032]" style={{height:`${h}%`,opacity:w.score===null?.12:1}}/></div><span className="text-[11px] text-zinc-500">{w.label}{isCurrent?"*":""}</span></div>;})}</div>{currentWeekInProgress&&<p className="mt-4 text-xs text-zinc-600">* Current week is still in progress. Live score is shown, but week-over-week interpretation waits until the week closes.</p>}</section>
<section className="rounded-2xl border border-zinc-800 p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">8-week volume telemetry</h2><p className="mt-1 text-sm text-zinc-500">Total training volume from working, top, and backoff sets. Warmups are excluded. Includes imported history.</p></div><div className="text-left sm:text-right"><p className="text-xs uppercase tracking-wider text-zinc-600">{latestVolumeIsCurrent?"Current week volume":"Latest vs prior trained week"}</p><p className={`mt-1 font-bold ${volumeChange!==null&&volumeChange>0?"phat-accent":"text-zinc-300"}`}>{latestVolumeIsCurrent&&latestVolume?`${Math.round(latestVolume.volume).toLocaleString()} lb so far`:volumeChange===null?"N/A":`${volumeChange>0?"+":""}${volumeChange.toFixed(1)}%`}</p>{latestVolumeIsCurrent&&<p className="mt-1 text-xs text-zinc-600">Comparison available when the week closes.</p>}</div></div><div className="mt-8 flex h-64 items-end gap-2 sm:gap-4">{weeks.map(w=>{const h=w.volume<=0?2:Math.max(6,(w.volume/maxVolume)*100),isCurrent=!!currentWeek&&w.key===currentWeek.key&&currentWeekInProgress;return <div key={w.key} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="max-w-full truncate text-[10px] font-semibold text-zinc-300 sm:text-xs" title={`${Math.round(w.volume).toLocaleString()} lb`}>{w.volume>0?formatVolume(w.volume):"—"}</span><div className="flex h-48 w-full items-end rounded-lg bg-zinc-900 p-1"><div className="w-full rounded-md bg-[#ff0032]" style={{height:`${h}%`,opacity:w.volume<=0?.12:1}}/></div><span className="text-[11px] text-zinc-500">{w.label}{isCurrent?"*":""}</span></div>;})}</div><p className="mt-4 text-xs text-zinc-600">Volume = weight × full reps across scored training sets. Partial reps are not added as full-rep volume.{currentWeekInProgress?" * Current week is shown live and is not compared with a completed prior week until it closes.":""}</p></section>
<section className="flex flex-col gap-3">{weeks.slice().reverse().map(w=>{const isCurrent=!!currentWeek&&w.key===currentWeek.key&&currentWeekInProgress;return <article key={w.key} className="rounded-xl border border-zinc-800 p-4"><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">Week of {w.start.toLocaleDateString()} {isCurrent&&<span className="ml-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">In progress</span>}</p><p className="mt-1 text-xs text-zinc-500">{w.completed} completed · {w.score===null?(w.completed>0?"baseline history · no comparable score yet":"no workouts"):`${w.scored} scored workout${w.scored===1?"":"s"}`}</p><p className="mt-1 text-xs text-zinc-500">Volume: {w.volume>0?`${Math.round(w.volume).toLocaleString()} lb`:"—"}</p></div><p className="text-2xl font-bold">{w.score===null?"—":`${w.score}%`}</p></div></article>})}</section><Link href="/" className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Back to Dashboard</Link></main>;
}
