"use client";

import { useEffect } from "react";
import { sharePngWithFallback } from "@/features/sharing/shareImage";

function esc(v:string){return v.replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]??c));}
const LOGO="/branding/PHATbot%20ICON.png";

async function loadImage(src:string){const image=new Image();image.src=src;try{await image.decode()}catch{await new Promise<void>((res,rej)=>{image.onload=()=>res();image.onerror=rej})}return image}

function compactResult(raw:string){
  const direct=raw.match(/(\d+(?:\.\d+)?\s*(?:lb|kg))\s*[×x]\s*(\d+)/i);
  if(direct)return `${direct[1]} × ${direct[2]}`;
  const rep=raw.match(/rep pr at\s*(\d+(?:\.\d+)?\s*(?:lb|kg))\s*:\s*(\d+)\s*reps?/i);
  if(rep)return `${rep[1]} × ${rep[2]}`;
  const pct=raw.match(/[+-]?\d+(?:\.\d+)?%/);
  if(pct)return pct[0];
  return raw.length>42?`${raw.slice(0,39).trim()}…`:raw;
}

function splitLines(text:string,maxChars:number,maxLines:number){const words=text.trim().split(/\s+/);const lines:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(next.length<=maxChars||!line)line=next;else{lines.push(line);line=word;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);if(words.join(" ").length>lines.join(" ").length&&lines.length)lines[lines.length-1]=`${lines[lines.length-1].replace(/…$/,'').slice(0,Math.max(1,maxChars-1)).trim()}…`;return lines}
function svgTextLines(lines:string[],x:number,startY:number,lineHeight:number,fontSize:number,fill:string,weight=900){return lines.map((line,i)=>`<text x="${x}" y="${startY+i*lineHeight}" text-anchor="middle" font-family="Arial Black,Arial" font-size="${fontSize}" font-weight="${weight}" fill="${fill}">${esc(line)}</text>`).join("")}

function cardSvg(title:string,result:string){const safeResult=compactResult(result),titleLines=splitLines(title,24,2),resultLines=splitLines(safeResult,20,2);const titleSize=titleLines.join("").length>28?50:64,resultSize=resultLines.join("").length>24?64:88;return `<svg xmlns="http://www.w3.org/2000/svg" width="920" height="760" viewBox="0 0 920 760"><defs><linearGradient id="cardBg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#240007"/><stop offset=".42" stop-color="#08090b"/><stop offset="1" stop-color="#090a0c"/></linearGradient></defs><rect x="10" y="10" width="900" height="740" rx="48" fill="url(#cardBg)" stroke="#ff1745" stroke-width="5"/><text x="460" y="92" text-anchor="middle" font-family="Arial Black,Arial" font-size="30" font-weight="900" letter-spacing="8" fill="#ff3154">PHATBOT WIN CARD</text><text x="460" y="166" text-anchor="middle" font-family="Arial,Helvetica" font-size="25" font-weight="800" letter-spacing="6" fill="#f2f2f2">BEEP BOOP — NEW BEST DETECTED</text>${svgTextLines(titleLines,460,titleLines.length===1?330:305,66,titleSize,"#f7f7f7")}${svgTextLines(resultLines,460,resultLines.length===1?465:445,84,resultSize,"#ff1745")}<text x="460" y="603" text-anchor="middle" font-family="Arial Black,Arial" font-size="31" font-weight="900" fill="#f7f7f7">MILESTONE LOGGED. HARDWARE</text><text x="460" y="654" text-anchor="middle" font-family="Arial Black,Arial" font-size="31" font-weight="900" fill="#f7f7f7">FUNCTIONING BEAUTIFULLY.</text></svg>`}

async function makeCard(title:string,result:string){const logo=await loadImage(LOGO);const cardUrl=URL.createObjectURL(new Blob([cardSvg(title,result)],{type:"image/svg+xml;charset=utf-8"}));let card:HTMLImageElement;try{card=await loadImage(cardUrl)}finally{URL.revokeObjectURL(cardUrl)}const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");if(!x)throw new Error("Canvas unavailable");x.fillStyle="#050506";x.fillRect(0,0,c.width,c.height);const grad=x.createRadialGradient(540,650,80,540,650,720);grad.addColorStop(0,"rgba(255,0,50,.16)");grad.addColorStop(1,"rgba(255,0,50,0)");x.fillStyle=grad;x.fillRect(0,0,c.width,c.height);x.save();x.globalAlpha=.05;for(let row=-1;row<6;row++){for(let col=-1;col<5;col++){const size=150,px=col*260+(row%2?120:-10),py=row*260;x.drawImage(logo,px,py,size,size)}}x.restore();x.drawImage(logo,465,72,150,150);x.drawImage(card,80,300,920,760);x.fillStyle="#777";x.font="700 23px Arial";x.textAlign="center";x.fillText("PHATBOT • TRAIN. TRACK. IMPROVE.",540,1185);return await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("PNG generation failed")),"image/png",1))}

async function shareCard(title:string,result:string){const blob=await makeCard(title,result);await sharePngWithFallback(blob,{fileName:"phatbot-win.png",title:"PHATBOT Win Card",text:`${title}: ${compactResult(result)}`})}

function openMenu(title:string,result:string){window.getSelection()?.removeAllRanges();document.querySelector("[data-phatbot-share-menu]")?.remove();const wrap=document.createElement("div");wrap.dataset.phatbotShareMenu="true";wrap.className="fixed inset-0 z-[100] flex items-end bg-black/60 p-4 backdrop-blur-sm";wrap.innerHTML=`<div class="mx-auto w-full max-w-md rounded-3xl border border-zinc-800 bg-[#090909] p-5 shadow-2xl"><div class="mb-4"><p class="text-[10px] font-black uppercase tracking-[.2em] text-[#ff0032]">PHATBOT SHARE</p><p class="mt-1 text-lg font-black text-white">${esc(title)}</p><p class="mt-1 text-xs text-zinc-500">${esc(compactResult(result))}</p></div><div class="grid gap-2"><button data-action="share" class="rounded-xl bg-[#ff0032] px-4 py-3 text-sm font-black text-white">SHARE IMAGE</button><button data-action="cancel" class="px-4 py-3 text-xs font-black uppercase tracking-wider text-zinc-500">Cancel</button></div><p class="mt-2 text-center text-[10px] leading-relaxed text-zinc-600">Share opens the native phone sheet for saving to Photos or sending to your apps.</p></div>`;wrap.addEventListener("click",async e=>{const action=(e.target as HTMLElement).closest("button")?.getAttribute("data-action");if(!action){if(e.target===wrap)wrap.remove();return}if(action==="cancel"){wrap.remove();return}try{await shareCard(title,result)}finally{wrap.remove()}});document.body.appendChild(wrap)}

function enableLongPress(target:HTMLElement,title:string,result:string){if(target.dataset.phatbotLongpress)return;target.dataset.phatbotLongpress="true";target.style.touchAction="pan-y";target.style.userSelect="none";(target.style as any).webkitUserSelect="none";(target.style as any).webkitTouchCallout="none";let timer:number|undefined,moved=false;const clear=()=>{if(timer)window.clearTimeout(timer);timer=undefined};target.addEventListener("contextmenu",e=>e.preventDefault());target.addEventListener("pointerdown",()=>{moved=false;clear();window.getSelection()?.removeAllRanges();timer=window.setTimeout(()=>{if(!moved)openMenu(title,result)},550)});target.addEventListener("pointermove",()=>{moved=true;clear()});target.addEventListener("pointerup",clear);target.addEventListener("pointercancel",clear)}

export default function ReportShareActions(){useEffect(()=>{const attach=()=>{const main=document.querySelector("main");if(!main)return;main.querySelectorAll("[data-phatbot-share]").forEach(n=>n.remove());const sections=[...main.querySelectorAll<HTMLElement>("section")];const win=sections.find(s=>(s.textContent??"").includes("PHATBOT WIN CARD"));if(win){const title=win.querySelector("h2")?.textContent?.trim()??"Personal Record",result=[...win.querySelectorAll("p")].map(p=>p.textContent?.trim()??"").find(v=>/\d+\s*(lb|kg)\s*[×x]\s*\d+/i.test(v))??"New PR";enableLongPress(win,title,result)}const prs=sections.find(s=>/Personal Records/i.test(s.textContent??""));if(prs)for(const card of [...prs.querySelectorAll<HTMLElement>("div.rounded-xl")]){const ps=[...card.querySelectorAll("p")].map(p=>p.textContent?.trim()??"").filter(Boolean);if(ps.length>=2)enableLongPress(card,ps[0],ps[1])}for(const sec of sections){const t=sec.textContent??"";if(t.includes("Progressive Overload Score")){const m=t.match(/Progressive Overload Score\s*(BASELINE|\d+%)/i)?.[1];if(m&&m!=="BASELINE"&&parseFloat(m)>50)enableLongPress(sec,"Progressive Overload Win",m)}if(t.includes("Training Volume vs Last Workout")){const m=t.match(/Training Volume vs Last Workout\s*(N\/A|[+-]?\d+(?:\.\d+)?%)/i)?.[1];if(m&&m!=="N/A"&&parseFloat(m)>0)enableLongPress(sec,"Training Volume Win",m)}}};attach();const o=new MutationObserver(attach);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);return null;}
