"use client";

import { useEffect } from "react";

function esc(v:string){return v.replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]??c));}
const LOGO="/branding/PHATbot%20ICON.png";

async function loadImage(src:string){const image=new Image();image.src=src;try{await image.decode()}catch{await new Promise<void>((res,rej)=>{image.onload=()=>res();image.onerror=rej})}return image}

function cardSvg(title:string,result:string){return `<svg xmlns="http://www.w3.org/2000/svg" width="920" height="760" viewBox="0 0 920 760"><defs><linearGradient id="cardBg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#240007"/><stop offset=".42" stop-color="#08090b"/><stop offset="1" stop-color="#090a0c"/></linearGradient></defs><rect x="10" y="10" width="900" height="740" rx="48" fill="url(#cardBg)" stroke="#ff1745" stroke-width="5"/><text x="460" y="95" text-anchor="middle" font-family="Arial Black,Arial" font-size="30" font-weight="900" letter-spacing="8" fill="#ff3154">PHATBOT WIN CARD</text><text x="460" y="175" text-anchor="middle" font-family="Arial,Helvetica" font-size="25" font-weight="800" letter-spacing="6" fill="#f2f2f2">BEEP BOOP — NEW BEST DETECTED</text><text x="460" y="330" text-anchor="middle" font-family="Arial Black,Arial" font-size="64" font-weight="900" fill="#f7f7f7">${esc(title)}</text><text x="460" y="455" text-anchor="middle" font-family="Arial Black,Arial" font-size="92" font-weight="900" fill="#ff1745">${esc(result)}</text><text x="460" y="590" text-anchor="middle" font-family="Arial Black,Arial" font-size="32" font-weight="900" fill="#f7f7f7">MILESTONE LOGGED. HARDWARE</text><text x="460" y="645" text-anchor="middle" font-family="Arial Black,Arial" font-size="32" font-weight="900" fill="#f7f7f7">FUNCTIONING BEAUTIFULLY.</text></svg>`}

async function makeCard(title:string,result:string){const [logo,card]=await Promise.all([loadImage(LOGO),loadImage(URL.createObjectURL(new Blob([cardSvg(title,result)],{type:"image/svg+xml;charset=utf-8"})))]);const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");if(!x)throw new Error("Canvas unavailable");x.fillStyle="#050506";x.fillRect(0,0,c.width,c.height);const grad=x.createRadialGradient(540,650,80,540,650,720);grad.addColorStop(0,"rgba(255,0,50,.16)");grad.addColorStop(1,"rgba(255,0,50,0)");x.fillStyle=grad;x.fillRect(0,0,c.width,c.height);x.save();x.globalAlpha=.055;for(let row=-1;row<6;row++){for(let col=-1;col<5;col++){const size=150,px=col*260+(row%2?120:-10),py=row*260;x.drawImage(logo,px,py,size,size)}}x.restore();x.drawImage(card,80,285,920,760);x.drawImage(logo,458,205,164,164);x.fillStyle="#777";x.font="700 23px Arial";x.textAlign="center";x.fillText("PHATBOT • TRAIN. TRACK. IMPROVE.",540,1165);return await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("PNG generation failed")),"image/png",1))}

async function shareCard(title:string,result:string){const blob=await makeCard(title,result),file=new File([blob],"phatbot-win.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:`PHATBOT ${title}`,text:`${title}: ${result}`,files:[file]});return}const href=URL.createObjectURL(blob),a=document.createElement("a");a.href=href;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000)}

function openMenu(title:string,result:string){document.querySelector("[data-phatbot-share-menu]")?.remove();const wrap=document.createElement("div");wrap.dataset.phatbotShareMenu="true";wrap.className="fixed inset-0 z-[100] flex items-end bg-black/60 p-4 backdrop-blur-sm";wrap.innerHTML=`<div class="mx-auto w-full max-w-md rounded-3xl border border-zinc-800 bg-[#090909] p-5 shadow-2xl"><div class="mb-4"><p class="text-[10px] font-black uppercase tracking-[.2em] text-[#ff0032]">PHATBOT SHARE</p><p class="mt-1 text-lg font-black text-white">${esc(title)}</p><p class="mt-1 text-xs text-zinc-500">${esc(result)}</p></div><div class="grid gap-2"><button data-action="share" class="rounded-xl bg-[#ff0032] px-4 py-3 text-sm font-black text-white">SHARE IMAGE</button><button data-action="cancel" class="px-4 py-3 text-xs font-black uppercase tracking-wider text-zinc-500">Cancel</button></div><p class="mt-2 text-center text-[10px] leading-relaxed text-zinc-600">Use the phone share sheet to save the image or send it to Instagram, Threads, Facebook, Messages, and more.</p></div>`;wrap.addEventListener("click",async e=>{const action=(e.target as HTMLElement).closest("button")?.getAttribute("data-action");if(!action){if(e.target===wrap)wrap.remove();return}if(action==="cancel"){wrap.remove();return}try{await shareCard(title,result)}finally{wrap.remove()}});document.body.appendChild(wrap)}

function enableLongPress(target:HTMLElement,title:string,result:string){if(target.dataset.phatbotLongpress)return;target.dataset.phatbotLongpress="true";target.style.touchAction="pan-y";let timer:number|undefined,moved=false;const clear=()=>{if(timer)window.clearTimeout(timer);timer=undefined};target.addEventListener("pointerdown",()=>{moved=false;clear();timer=window.setTimeout(()=>{if(!moved)openMenu(title,result)},550)});target.addEventListener("pointermove",()=>{moved=true;clear()});target.addEventListener("pointerup",clear);target.addEventListener("pointercancel",clear)}

export default function ReportShareActions(){useEffect(()=>{const attach=()=>{const main=document.querySelector("main");if(!main)return;main.querySelectorAll("[data-phatbot-share]").forEach(n=>n.remove());const sections=[...main.querySelectorAll<HTMLElement>("section")];const win=sections.find(s=>(s.textContent??"").includes("PHATBOT WIN CARD"));if(win){const title=win.querySelector("h2")?.textContent?.trim()??"Personal Record",result=[...win.querySelectorAll("p")].map(p=>p.textContent?.trim()??"").find(v=>/\d+\s*(lb|kg)\s*[×x]\s*\d+/i.test(v))??"New PR";enableLongPress(win,title,result)}const prs=sections.find(s=>/Personal Records/i.test(s.textContent??""));if(prs)for(const card of [...prs.querySelectorAll<HTMLElement>("div.rounded-xl")]){const ps=[...card.querySelectorAll("p")].map(p=>p.textContent?.trim()??"").filter(Boolean);if(ps.length>=2)enableLongPress(card,ps[0],ps[1])}for(const sec of sections){const t=sec.textContent??"";if(t.includes("Progressive Overload Score")){const m=t.match(/Progressive Overload Score\s*(BASELINE|\d+%)/i)?.[1];if(m&&m!=="BASELINE"&&parseFloat(m)>50)enableLongPress(sec,"Progressive Overload Win",m)}if(t.includes("Training Volume vs Last Workout")){const m=t.match(/Training Volume vs Last Workout\s*(N\/A|[+-]?\d+(?:\.\d+)?%)/i)?.[1];if(m&&m!=="N/A"&&parseFloat(m)>0)enableLongPress(sec,"Training Volume Win",m)}}};attach();const o=new MutationObserver(attach);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);return null;}
