"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type Session={id:string;workout_name_snapshot:string;completed_at:string};type StoredScore={workout_session_id:string;score:number};type ExerciseScore={workout_session_id:string;result:"progression"|"neutral"|"regression"|"baseline"};type Point={id:string;date:string;score:number|null;status:"scored"|"baseline"|"pending"};
const key=(n:string)=>n.trim().toLowerCase().replace(/\s+/g," ");const path=(p:{x:number;y:number}[])=>p.map((v,i)=>`${i?"L":"M"} ${v.x} ${v.y}`).join(" ");
export default function CoachWorkoutTrends(){const{athleteId}=useParams<{athleteId:string}>();const[sessions,setSessions]=useState<Session[]>([]),[scores,setScores]=useState<Record<string,number>>({}),[states,setStates]=useState<Record<string,ExerciseScore["result"][]>>({}),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
useEffect(()=>{const s=createSupabaseBrowserClient();async function load(){const{data:{user}}=await s.auth.getUser();if(!user){location.href="/auth/coach";return;}const{data:link}=await s.from("coach_athletes").select("athlete_user_id").eq("coach_user_id",user.id).eq("athlete_user_id",athleteId).eq("active",true).maybeSingle();if(!link){setMessage("You do not have access to this athlete.");setLoading(false);return;}const[{data,error},{data:ws,error:we},{data:es,error:ee}]=await Promise.all([s.from("workout_sessions").select("id,workout_name_snapshot,completed_at").eq("athlete_user_id",athleteId).eq("status","completed").order("completed_at",{ascending:true}),s.from("workout_scores").select("workout_session_id,score").eq("athlete_user_id",athleteId),s.from("exercise_scores").select("workout_session_id,result").eq("athlete_user_id",athleteId)]);if(error||we||ee){setMessage(error?.message??we?.message??ee?.message??"Unable to load workout trends.");setLoading(false);return;}const rows=(data??[])as Session[];setSessions(rows);setScores(Object.fromEntries(((ws??[])as StoredScore[]).map(x=>[x.workout_session_id,Math.round(Number(x.score)*100)])));const map:Record<string,ExerciseScore["result"][]>={};for(const x of(es??[])as ExerciseScore[])(map[x.workout_session_id]??=[]).push(x.result);setStates(map);if(rows.length)setSelected(key(rows.at(-1)!.workout_name_snapshot));setLoading(false);}load();},[athleteId]);
const workouts=useMemo(()=>Array.from(new Map(sessions.map(x=>[key(x.workout_name_snapshot),x.workout_name_snapshot])).entries()).sort((a,b)=>a[1].localeCompare(b[1])),[sessions]);const points=useMemo<Point[]>(()=>sessions.filter(x=>key(x.workout_name_snapshot)===selected).map(x=>{const score=scores[x.id]??null,r=states[x.id]??[];return{id:x.id,date:x.completed_at,score,status:score!==null?"scored":r.length&&r.every(v=>v==="baseline")?"baseline":"pending"};}),[sessions,scores,states,selected]);const scored=points.filter(x=>x.score!==null),coords=scored.map((p,i)=>({x:scored.length===1?50:i/(scored.length-1)*100,y:100-(p.score??0)})),latest=scored.at(-1),prior=scored.at(-2),delta=latest&&prior?(latest.score??0)-(prior.score??0):null;
if(loading)return <main className="mx-auto min-h-screen max-w-3xl px-6 py-12">Beep boop... indexing athlete workout history.</main>;return <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-6 px-6 py-10"><header><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Coach · Workout Trends</p><h1 className="mt-2 text-3xl font-bold">Workout telemetry</h1><p className="mt-2 text-zinc-400">Full imported and PHATBOT-recorded history for this athlete, grouped by workout.</p></header>{message&&<p className="rounded-xl border border-zinc-800 p-4">{message}</p>}<label className="flex flex-col gap-2 text-sm font-semibold">Workout<select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3">{workouts.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label>{points.length>0&&<><section className="grid gap-3 sm:grid-cols-3"><Metric label="Sessions" value={String(points.length)}/><Metric label="Latest Scored" value={latest?`${latest.score}%`:"N/A"}/><Metric label="vs Prior Scored" value={delta===null?"N/A":`${delta>=0?"+":""}${delta} pts`}/></section><section className="rounded-2xl border border-zinc-800 p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">🤖 PO Score Signal</p><div className="mt-5 h-56"><svg viewBox="0 0 100 100" className="h-full w-full" preserveAspectRatio="none"><line x1="0" y1="50" x2="100" y2="50" stroke="currentColor" opacity=".1"/><path d={path(coords)} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{coords.map((c,i)=><circle key={i} cx={c.x} cy={c.y} r="1.8" fill="currentColor"/>)}</svg></div><div className="flex justify-between text-xs text-zinc-500"><span>{scored[0]?new Date(scored[0].date).toLocaleDateString():"No comparable scores"}</span><span>{scored.at(-1)?new Date(scored.at(-1)!.date).toLocaleDateString():""}</span></div></section><section className="flex flex-col gap-3">{points.slice().reverse().map(p=><Link key={p.id} href={`/coach/athletes/${athleteId}/sessions/${p.id}`} className="rounded-xl border border-zinc-800 p-4 transition hover:border-[#ff0032]"><div className="flex justify-between gap-4"><div><p className="font-semibold">{new Date(p.date).toLocaleDateString()}</p><p className="mt-1 text-xs text-zinc-500">View full PHATBOT report →</p></div><p className="text-xl font-bold">{p.status==="baseline"?"Baseline":p.status==="pending"?"Review":`${p.score}%`}</p></div></Link>)}</section></>}<div className="grid gap-3 sm:grid-cols-2"><Link href={`/coach/athletes/${athleteId}/trends/exercises`} className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Exercise Trends</Link><Link href={`/coach/athletes/${athleteId}`} className="rounded-lg bg-white px-5 py-3 text-center font-semibold text-black">Back to Athlete</Link></div></main>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-zinc-800 p-5"><p className="text-xs uppercase tracking-widest text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
