"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {createSupabaseBrowserClient} from "@/lib/supabase";
const KEY="phatbot:pending-room-code";
type JoinResult={room_id:string;workout_session_id:string;room_name:string};
export default function TrainTogetherJoinPage(){const params=useParams<{code:string}>(),code=(params.code??"").toUpperCase(),[state,setState]=useState<"checking"|"joining"|"joined"|"error">("checking"),[message,setMessage]=useState("PHATBOT is finding the workout room..."),[joined,setJoined]=useState<JoinResult|null>(null);
useEffect(()=>{let active=true;(async()=>{const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!active)return;if(!user){try{localStorage.setItem(KEY,code)}catch{}window.location.href="/auth";return;}setState("joining");setMessage("Room found. Loading your copy of the workout...");const{data,error}=await (s as any).rpc("join_live_workout_room_and_start",{p_join_code:code});if(!active)return;if(error){setState("error");setMessage(error.message||"PHATBOT could not join this room.");return;}const row=((data??[])[0]??null) as JoinResult|null;if(!row?.workout_session_id){setState("error");setMessage("PHATBOT joined the room but could not start your workout.");return;}try{localStorage.removeItem(KEY)}catch{}setJoined(row);setState("joined");setMessage("You're in the room. Your workout is ready.");})();return()=>{active=false}},[code]);
function openWorkout(){if(joined?.workout_session_id)window.location.assign(`/sessions/${joined.workout_session_id}`)}
return <main className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center px-6 py-12 text-center"><p className="text-xs font-black uppercase tracking-[.24em] text-[#ff0032]">PHATBOT SOCIAL</p><h1 className="mt-3 text-4xl font-black">Train Together</h1>{state==="joined"?<div className="mt-7 grid h-20 w-20 place-items-center rounded-full border-2 border-[#ff0032] bg-[#ff0032]/10 text-4xl">✓</div>:<div className={`mt-7 h-16 w-16 rounded-full border-4 ${state==="error"?"border-zinc-700":"animate-pulse border-[#ff0032]"}`}/>}<p className="mt-6 text-sm leading-6 text-zinc-400">{message}</p>{state==="joined"&&joined&&<><div className="mt-5 w-full rounded-2xl border border-zinc-800 bg-zinc-950 p-5 text-left"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff0032]">Room Joined</p><p className="mt-2 text-xl font-black">{joined.room_name||"Train Together Room"}</p><p className="mt-2 text-sm text-zinc-400">You are connected to this room. PHATBOT created your independent workout so your sets, history and score stay yours.</p></div><button onClick={openWorkout} className="mt-5 w-full rounded-xl bg-[#ff0032] px-5 py-4 font-black text-white">OPEN MY WORKOUT →</button></>}<p className="mt-3 font-mono text-xs font-black tracking-[.18em] text-zinc-600">ROOM {code}</p>{state==="error"&&<div className="mt-7 grid w-full gap-3"><button onClick={()=>window.location.reload()} className="rounded-xl bg-[#ff0032] px-5 py-3 font-black text-white">TRY AGAIN</button><button onClick={()=>window.location.href="/workouts"} className="rounded-xl border border-zinc-700 px-5 py-3 font-bold">Back to PHATBOT Train</button></div>}</main>}
