"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {createSupabaseBrowserClient} from "@/lib/supabase";
const KEY="phatbot:pending-room-code";
type JoinResult={room_id:string;workout_session_id:string;room_name:string};
export default function TrainTogetherJoinPage(){const params=useParams<{code:string}>(),code=(params.code??"").toUpperCase(),[state,setState]=useState<"checking"|"joining"|"error">("checking"),[message,setMessage]=useState("PHATBOT is finding the workout room...");
useEffect(()=>{let active=true;(async()=>{const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!active)return;if(!user){try{localStorage.setItem(KEY,code)}catch{}window.location.href="/auth";return;}setState("joining");setMessage("Room found. Cloning the workout into your account...");const{data,error}=await (s as any).rpc("join_live_workout_room_and_start",{p_join_code:code});if(!active)return;if(error){setState("error");setMessage(error.message||"PHATBOT could not join this room.");return;}const row=((data??[])[0]??null) as JoinResult|null;if(!row?.workout_session_id){setState("error");setMessage("PHATBOT joined the room but could not start your workout.");return;}try{localStorage.removeItem(KEY)}catch{}window.location.href=`/sessions/${row.workout_session_id}`})();return()=>{active=false}},[code]);
return <main className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center px-6 py-12 text-center"><p className="text-xs font-black uppercase tracking-[.24em] text-[#ff0032]">PHATBOT SOCIAL</p><h1 className="mt-3 text-4xl font-black">Train Together</h1><div className={`mt-7 h-16 w-16 rounded-full border-4 ${state==="error"?"border-zinc-700":"animate-pulse border-[#ff0032]"}`}/><p className="mt-6 text-sm leading-6 text-zinc-400">{message}</p><p className="mt-3 font-mono text-xs font-black tracking-[.18em] text-zinc-600">ROOM {code}</p>{state==="error"&&<div className="mt-7 grid w-full gap-3"><button onClick={()=>window.location.reload()} className="rounded-xl bg-[#ff0032] px-5 py-3 font-black text-white">TRY AGAIN</button><button onClick={()=>window.location.href="/workouts"} className="rounded-xl border border-zinc-700 px-5 py-3 font-bold">Back to PHATBOT Train</button></div>}</main>}
