"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {consistencyLabel,nutritionConsistency,type NutritionDay} from "@/features/nutrition/nutrition";
import {createSupabaseBrowserClient} from "@/lib/supabase";

export default function NutritionProgressPage(){
 const [days,setDays]=useState<NutritionDay[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;void(async()=>{try{const client=createSupabaseBrowserClient();const {data:{user}}=await client.auth.getUser();if(!user){window.location.href="/auth";return;}const since=new Date();since.setDate(since.getDate()-27);const date=since.toISOString().slice(0,10);const {data,error}=await client.from("health_nutrition_daily").select("nutrition_date,energy_kcal,protein_g,carbohydrate_g,fat_g,source,source_origins").eq("athlete_user_id",user.id).gte("nutrition_date",date).order("nutrition_date",{ascending:false});if(error)throw error;if(active)setDays((data??[]) as NutritionDay[]);}catch{if(active)setFailed(true);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const recent=useMemo(()=>days.slice(0,7),[days]),metric=useMemo(()=>nutritionConsistency(recent,7),[recent]);
 return <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-6 px-4 py-8 sm:px-6"><Link href="/progress" className="min-h-11 py-2 text-sm font-bold text-zinc-400">← Progress</Link><header><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff0032]">PHATBOT Nutrition</p><h1 className="mt-2 text-3xl font-black">Consistency over restriction.</h1><p className="mt-2 text-sm leading-6 text-zinc-400">PHATBOT looks for repeatable eating patterns that support your goal. A low-calorie day is not automatically a win, and one high day is not a failure.</p></header>
 {loading?<section className="rounded-2xl border border-zinc-800 p-5 text-zinc-500">Reading your nutrition history…</section>:failed?<section className="rounded-2xl border border-zinc-800 p-5"><h2 className="font-black">Nutrition history is unavailable.</h2><p className="mt-2 text-sm text-zinc-500">Your saved data has not been changed.</p></section>:days.length===0?<section className="rounded-2xl border border-zinc-800 p-5"><h2 className="font-black">Start building your baseline.</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Log nutrition in a connected health source. Missing days stay unknown—PHATBOT will never treat them as zero calories.</p></section>:<>
 <section className="rounded-2xl border border-[#ff0032]/50 bg-[#ff0032]/5 p-5"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff0032]">7-Day Pattern</p><h2 className="mt-2 text-3xl font-black">{consistencyLabel(metric)}</h2><p className="mt-2 text-sm text-zinc-300">{metric.recordedDays} of 7 days recorded. {metric.recordedDays<7?"Unrecorded days are excluded, not counted as zero.":""}</p></section>
 <section className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-zinc-800 p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Avg energy</p><p className="mt-2 text-2xl font-black">{metric.averageCalories===null?"—":`${Math.round(metric.averageCalories).toLocaleString()} kcal`}</p><p className="mt-1 text-xs text-zinc-600">{metric.calorieDays} recorded day{metric.calorieDays===1?"":"s"}</p></div><div className="rounded-2xl border border-zinc-800 p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Avg protein</p><p className="mt-2 text-2xl font-black">{metric.averageProteinG===null?"—":`${Math.round(metric.averageProteinG)} g`}</p><p className="mt-1 text-xs text-zinc-600">{metric.proteinDays} recorded day{metric.proteinDays===1?"":"s"}</p></div></section>
 <section className="rounded-2xl border border-zinc-800 p-5"><h2 className="font-black">Recent days</h2><div className="mt-3">{recent.map(day=><div key={`${day.source}:${day.nutrition_date}`} className="flex items-center justify-between border-b border-zinc-900 py-3 last:border-0"><div><p className="text-sm font-bold">{new Date(day.nutrition_date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</p><p className="mt-1 text-xs text-zinc-600">{day.source==="healthkit"?"Apple Health":day.source==="health_connect"?"Health Connect":"Connected source"}</p></div><div className="text-right"><p className="text-sm font-black">{day.energy_kcal==null?"Energy —":`${Math.round(day.energy_kcal).toLocaleString()} kcal`}</p><p className="mt-1 text-xs text-zinc-500">{day.protein_g==null?"Protein —":`${Math.round(day.protein_g)} g protein`}</p></div></div>)}</div></section>
 </>}
 <p className="text-xs leading-5 text-zinc-600">Nutrition patterns are context, not a diagnosis. PHATBOT will use performance, recovery, body-weight and nutrition signals together before suggesting that fueling may need attention.</p></main>;
}
