"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { calculateStrengthChange } from "@/features/scoring/strengthChange";

type Profile = { display_name: string | null };
type LatestWorkout = { id: string; workout_id: string; workout_name_snapshot: string; completed_at: string | null };
type RawSet = { weight: number; reps: number; set_type: string };
type ExerciseSession = { exercise_id: string; sets: RawSet[] };

export default function HomePage() {
  const [loading, setLoading] = useState(true); const [signedIn, setSignedIn] = useState(false); const [profile, setProfile] = useState<Profile | null>(null); const [latestWorkout, setLatestWorkout] = useState<LatestWorkout | null>(null); const [weeklyCompleted, setWeeklyCompleted] = useState(0); const [latestStrength, setLatestStrength] = useState<number | null>(null);
  useEffect(() => { let active = true; const supabase = createSupabaseBrowserClient(); async function loadUser() { const { data: { user } } = await supabase.auth.getUser(); if (!active) return; if (!user) { setSignedIn(false); setLoading(false); return; } setSignedIn(true); const weekStart = new Date(); const day = weekStart.getDay(); const diff = day === 0 ? 6 : day - 1; weekStart.setDate(weekStart.getDate() - diff); weekStart.setHours(0, 0, 0, 0); const [profileResult, latestResult, weeklyResult] = await Promise.all([supabase.from("profiles").select("display_name").eq("id", user.id).single(), supabase.from("workout_sessions").select("id, workout_id, workout_name_snapshot, completed_at").eq("athlete_user_id", user.id).eq("status", "completed").order("completed_at", { ascending: false }).limit(1).maybeSingle(), supabase.from("workout_sessions").select("id", { count: "exact", head: true }).eq("athlete_user_id", user.id).eq("status", "completed").gte("completed_at", weekStart.toISOString())]);
      const latest = latestResult.data as LatestWorkout | null; let strength: number | null = null;
      if (latest?.completed_at) {
        const { data: previous } = await supabase.from("workout_sessions").select("id").eq("athlete_user_id", user.id).eq("workout_id", latest.workout_id).eq("status", "completed").lt("completed_at", latest.completed_at).order("completed_at", { ascending: false }).limit(1).maybeSingle();
        if (previous) {
          const [currentResult, previousResult] = await Promise.all([supabase.from("exercise_sessions").select("exercise_id, sets(weight,reps,set_type)").eq("workout_session_id", latest.id), supabase.from("exercise_sessions").select("exercise_id, sets(weight,reps,set_type)").eq("workout_session_id", previous.id)]);
          const current = (currentResult.data ?? []) as ExerciseSession[]; const prior = (previousResult.data ?? []) as ExerciseSession[];
          strength = calculateStrengthChange(current.map((exercise) => ({ exerciseId: exercise.exercise_id, sets: exercise.sets.map((set) => ({ weight: Number(set.weight), reps: set.reps, setType: set.set_type })) })), prior.map((exercise) => ({ exerciseId: exercise.exercise_id, sets: exercise.sets.map((set) => ({ weight: Number(set.weight), reps: set.reps, setType: set.set_type })) }))).percentageChange;
        }
      }
      if (active) { setProfile(profileResult.data); setLatestWorkout(latest); setWeeklyCompleted(weeklyResult.count ?? 0); setLatestStrength(strength); setLoading(false); } } loadUser(); const { data: listener } = supabase.auth.onAuthStateChange(() => { loadUser(); }); return () => { active = false; listener.subscription.unsubscribe(); }; }, []);
  async function signOut() { const supabase = createSupabaseBrowserClient(); await supabase.auth.signOut(); window.location.href = "/"; }
  if (loading) return <main className="mx-auto flex min-h-screen max-w-xl items-center px-6 py-12"><p className="text-zinc-300">Loading PHATBOT...</p></main>;
  if (!signedIn) return <main className="mx-auto flex min-h-screen max-w-xl flex-col justify-center gap-6 px-6 py-12"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-zinc-400">PHATBOT</p><h1 className="mt-2 text-4xl font-bold">Did you improve today?</h1><p className="mt-4 text-zinc-300">PHATBOT tracks progressive overload, workout scoring, personal records, and your performance over time.</p></div><Link href="/auth" className="rounded-lg bg-white px-5 py-3 text-center font-semibold text-black">Create Account / Sign In</Link></main>;
  return <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-8 px-6 py-10"><header className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-zinc-400">PHATBOT</p><h1 className="mt-2 text-3xl font-bold">Welcome{profile?.display_name ? `, ${profile.display_name}` : ""}.</h1><p className="mt-2 text-zinc-300">Your training dashboard is ready.</p></div><div className="flex gap-2"><Link href="/account" className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold">Account</Link><button onClick={signOut} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold">Sign Out</button></div></header><section className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-400">Latest Workout</p>{latestWorkout ? <><p className="mt-2 text-2xl font-semibold">{latestWorkout.workout_name_snapshot}</p><p className="mt-2 text-sm text-zinc-400">Completed {latestWorkout.completed_at ? new Date(latestWorkout.completed_at).toLocaleString() : "recently"}</p><div className="mt-4 rounded-lg bg-zinc-900 p-3"><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">Strength vs Prior</p><p className="mt-1 text-2xl font-bold">{latestStrength === null ? "N/A" : `${latestStrength >= 0 ? "+" : ""}${latestStrength.toFixed(1)}%`}</p></div><Link href={`/sessions/${latestWorkout.id}/report`} className="mt-4 inline-block text-sm font-semibold underline">View Report →</Link></> : <><p className="mt-2 text-2xl font-semibold">No workouts yet</p><p className="mt-2 text-sm text-zinc-400">Your first completed workout will appear here.</p></>}</div><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-400">This Week</p><p className="mt-2 text-2xl font-semibold">{weeklyCompleted} workout{weeklyCompleted === 1 ? "" : "s"}</p><p className="mt-2 text-sm text-zinc-400">See your weekly performance score and average strength change versus prior workouts.</p><div className="mt-4 flex flex-wrap gap-4"><Link href="/weekly" className="text-sm font-semibold underline">View Weekly Report →</Link><Link href="/progress" className="text-sm font-semibold underline">View Progress Trend →</Link></div></div></section><Link href="/workouts" className="rounded-lg bg-white px-5 py-3 text-center font-semibold text-black">Start Workout</Link></main>;
}
