"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
import {AthleteDashboardNav} from "@/components/AthleteDashboardNav";
import {RebuildDashboardStatus} from "@/components/RebuildDashboardStatus";
type Profile={display_name:string|null};type WorkoutTemplate={id:string;name:string;description:string|null;created_at:string;sort_order:number|null};type WorkoutSession={id:string;workout_id:string;workout_name_snapshot:string;completed_at:string};type ActiveWorkout={id:string;workout_name_snapshot:string;started_at:string};type CoachFeedback={workout_session_id:string;feedback:string;updated_at:string;workout_name:string|null};type PlateauSignal={exercise_id:string;exercise_name:string;consecutive_flat_sessions:number;change_percent:number|null};type SignalRead={signal_kind:"win"|"training";signal_key:string};
function trainingSignalKey(s:PlateauSignal){return`${s.exercise_id}:${s.consecutive_flat_sessions}`}
function athleteFacingDescription(description:string|null){if(!description)return null;if(/^Imported by coach\s+[0-9a-f-]{20,}$/i.test(description.trim()))return"Assigned by your coach";return description}
export default function HomePage(){const[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[loadError,setLoadError]=useState<string|null>(null),[profile,setProfile]=useState<Profile|null>(null),[workoutTemplates,setWorkoutTemplates]=useState<WorkoutTemplate[]>([]),[latestWorkout,setLatestWorkout]=useState<WorkoutSession|null>(null),[activeWorkout,setActiveWorkout]=useState<ActiveWorkout|null>(null),[latestCoachFeedback,setLatestCoachFeedback]=useState<CoachFeedback|null>(null),[plateauSignals,setPlateauSignals]=useState<PlateauSignal[]>([]);
useEffect(()=>{let mounted=true;const s=createSupabaseBrowserClient();async function load(){if(mounted){setLoading(true);setLoadError(null)}try{const{data:{user},error:authError}=await s.auth.getUser();if(authError)throw authError;if(!mounted)return;if(!user){setSignedIn(false);setLoading(false);return}setSignedIn(true);const[pr,templates,lr,ar,fr,ps,sr]=await Promise.all([s.from("profiles").select("display_name").eq("id",user.id).single(),s.from("workouts").select("id,name,description,created_at,sort_order").eq("athlete_user_id",user.id).eq("is_active",true).order("sort_order",{ascending:true,nullsFirst:false}).order("created_at",{ascending:true}),s.from("workout_sessions").select("id,workout_id,workout_name_snapshot,completed_at").eq("athlete_user_id",user.id).eq("status","completed").order("completed_at",{ascending:false}).limit(1).maybeSingle(),s.from("workout_sessions").select("id,workout_name_snapshot,started_at").eq("athlete_user_id",user.id).eq("status","in_progress").order("started_at",{ascending:false}).limit(1).maybeSingle(),s.from("coach_workout_feedback").select("workout_session_id,feedback,updated_at").eq("athlete_user_id",user.id).is("athlete_read_at",null).order("updated_at",{ascending:false}).limit(1).maybeSingle(),s.from("exercise_plateau_signals").select("exercise_id,exercise_name,consecutive_flat_sessions,change_percent").eq("athlete_user_id",user.id).eq("status","active").order("consecutive_flat_sessions",{ascending:false}).limit(10),s.from("athlete_signal_reads").select("signal_kind,signal_key").eq("athlete_user_id",user.id).eq("signal_kind","training")]);const criticalError=templates.error||lr.error||ar.error;if(criticalError)throw criticalError;let feedback:CoachFeedback|null=null;if(fr.data){const{data:w}=await s.from("workout_sessions").select("workout_name_snapshot").eq("id",fr.data.workout_session_id).eq("athlete_user_id",user.id).maybeSingle();feedback={...fr.data,workout_name:w?.workout_name_snapshot??null}as CoachFeedback}const readKeys=new Set(((sr.data??[])as SignalRead[]).map(r=>r.signal_key));if(!mounted)return;setProfile(pr.data);setWorkoutTemplates((templates.data??[])as WorkoutTemplate[]);setLatestWorkout(lr.data as WorkoutSession|null);setActiveWorkout(ar.data as ActiveWorkout|null);setLatestCoachFeedback(feedback);setPlateauSignals(((ps.data??[])as PlateauSignal[]).filter(x=>!readKeys.has(trainingSignalKey(x))).slice(0,3));setLoading(false)}catch(error){console.error("Dashboard load failed",error);if(mounted){setLoadError("PHATBOT couldn't load your training data.");setLoading(false)}}}load();const{data:l}=s.auth.onAuthStateChange(()=>load());return()=>{mounted=false;l.subscription.unsubscribe()}},[]);
async function signOut(){const s=createSupabaseBrowserClient();await s.auth.signOut();window.location.href="/"}async function markTrainingSignalRead(signal:PlateauSignal){const s=createSupabaseBrowserClient();const{data:{user}}=await s.auth.getUser();if(!user)return;await s.from("athlete_signal_reads").upsert({athlete_user_id:user.id,signal_kind:"training",signal_key:trainingSignalKey(signal),read_at:new Date().toISOString()},{onConflict:"athlete_user_id,signal_kind,signal_key"});setPlateauSignals(c=>c.filter(x=>trainingSignalKey(x)!==trainingSignalKey(signal)))}
if(loading)return<main className="mx-auto flex min-h-screen max-w-xl flex-col justify-center gap-4 px-6 py-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#ff0032]">PHATBOT</p><h1 className="text-2xl font-black">Loading your training data...</h1><div className="h-2 overflow-hidden rounded-full bg-zinc-900"><div className="h-full w-1/2 animate-pulse rounded-full bg-[#ff0032]"/></div><p className="text-sm text-zinc-400">Beep boop. Checking workouts, coaching signals, and recent performance.</p></main>;
if(loadError)return<main className="mx-auto flex min-h-screen max-w-xl flex-col justify-center gap-5 px-6 py-12"><div className="rounded-2xl border border-[#ff0032]/50 bg-[#ff0032]/5 p-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff0032]">PHATBOT CONNECTION ERROR</p><h1 className="mt-2 text-2xl font-black">Training data didn't load.</h1><p className="mt-3 text-zinc-300">{loadError} Your data has not been changed. Try the connection again.</p><button onClick={()=>window.location.reload()} className="mt-5 w-full rounded-lg bg-[#ff0032] px-5 py-3 font-bold text-white">Try Again</button></div><button onClick={signOut} className="text-sm font-semibold text-zinc-400 underline">Sign out</button></main>;
if(!signedIn)return<main className="mx-auto flex min-h-screen max-w-xl flex-col justify-center gap-6 px-6 py-12"><div><p className="text-sm font-bold uppercase tracking-[.25em] text-white">PHATBOT</p><h1 className="mt-2 text-4xl font-bold">Did you improve today?</h1><p className="mt-4 text-zinc-300">PHATBOT tracks progressive overload, workout scoring, personal records, and your performance over time.</p></div><Link href="/auth" className="rounded-lg bg-white px-5 py-3 text-center font-semibold text-black">Create Account / Sign In</Link></main>;
const visibleWorkoutTemplates=workoutTemplates.slice(0,3);
return<main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-8 px-4 py-8 sm:px-6 sm:py-10"><header className="flex items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">Welcome{profile?.display_name?`, ${profile.display_name}`:""}.</h1><p className="mt-2 text-zinc-300">Track. Compare. Celebrate. Coach. Adjust.</p></div><button onClick={signOut} className="shrink-0 rounded-lg border border-zinc-700 px-3 py-2 text-sm font-semibold">Sign Out</button></header>
<AthleteDashboardNav activeWorkoutId={activeWorkout?.id}/>
{activeWorkout&&<section className="rounded-2xl border border-[#ff0032]/50 bg-[#ff0032]/5 p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff0032]">Active Workout</p><h2 className="mt-2 text-2xl font-bold">{activeWorkout.workout_name_snapshot} is waiting.</h2><p className="mt-2 text-sm text-zinc-300">Your training data is saved. Pick up exactly where you left off.</p><Link href={`/sessions/${activeWorkout.id}`} className="mt-4 block rounded-lg bg-white px-5 py-3 text-center font-bold text-black">Resume Workout</Link></section>}
{(latestCoachFeedback||plateauSignals.length>0)&&<section className="flex flex-col gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff0032]">Active PHATBOT Coaching</p><h2 className="mt-1 text-xl font-bold">What needs your attention</h2></div>{latestCoachFeedback&&<Link href={`/sessions/${latestCoachFeedback.workout_session_id}/report`} className="block rounded-2xl border border-zinc-700 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Coach Transmission</p><p className="mt-2 font-bold">New feedback{latestCoachFeedback.workout_name?` on ${latestCoachFeedback.workout_name}`:""}</p><p className="mt-2 line-clamp-2 text-sm text-zinc-300">{latestCoachFeedback.feedback}</p><p className="mt-3 text-sm font-semibold">Read transmission →</p></Link>}{plateauSignals.map(signal=><Link key={trainingSignalKey(signal)} href={`/progress/exercises?exercise=${encodeURIComponent(signal.exercise_id)}`} onClick={()=>void markTrainingSignalRead(signal)} className="block rounded-2xl border border-zinc-800 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Training Signal</p><p className="mt-2 font-bold">{signal.exercise_name} has gone flat.</p><p className="mt-2 text-sm text-zinc-300">{signal.consecutive_flat_sessions} flat sessions detected. Review the exercise for coaching context.</p></Link>)}</section>}
<RebuildDashboardStatus/>
<section><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff0032]">Latest Workout Report</p><h2 className="mt-1 text-xl font-bold">Your most recent result</h2></div><div className="mt-3 rounded-2xl border border-zinc-800 p-5">{latestWorkout?<><p className="text-2xl font-semibold">{latestWorkout.workout_name_snapshot}</p><p className="mt-2 text-sm text-zinc-400">Completed {new Date(latestWorkout.completed_at).toLocaleString()}</p><Link href={`/sessions/${latestWorkout.id}/report`} className="mt-4 inline-block text-sm font-semibold underline">View Full Report →</Link></>:<><p className="font-bold">No completed workouts yet.</p><p className="mt-2 text-sm text-zinc-400">Complete your first workout and PHATBOT will build your performance history here.</p></>}</div></section>
<section className="flex flex-col gap-3"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff0032]">Your Training</p><h2 className="mt-1 text-xl font-bold">Workout Templates</h2></div><Link href="/workouts" className="text-sm font-semibold underline">View all →</Link></div>{workoutTemplates.length===0?<div className="rounded-2xl border border-zinc-800 p-5"><p className="font-bold">No workouts assigned yet.</p><p className="mt-2 text-sm text-zinc-400">Your training area is ready. Add a workout or wait for your coach to assign one.</p><Link href="/workouts" className="mt-4 inline-block text-sm font-bold underline">Open workouts →</Link></div>:<><div className="grid gap-3 sm:grid-cols-2">{visibleWorkoutTemplates.map(w=>{const description=athleteFacingDescription(w.description);return<Link key={w.id} href={`/workouts/${w.id}`} className="rounded-2xl border border-zinc-800 p-5 transition hover:border-[#ff0032]"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Ready to Train</p><h3 className="mt-2 text-xl font-black">{w.name}</h3>{description&&<p className="mt-2 line-clamp-2 text-sm text-zinc-400">{description}</p>}<p className="mt-4 text-sm font-bold">Open workout <span className="text-[#ff0032]">→</span></p></Link>})}</div>{workoutTemplates.length>visibleWorkoutTemplates.length&&<Link href="/workouts" className="mt-1 block rounded-xl border border-zinc-800 px-4 py-3 text-center text-sm font-semibold text-zinc-300">View all {workoutTemplates.length} workouts →</Link>}</>}</section></main>
