"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { scoreExercisePerformance, type PerformanceSet } from "@/features/scoring/progressiveOverload";
import { calculateStrengthChange } from "@/features/scoring/strengthChange";
import { calculateWeightedWorkoutScore } from "@/features/scoring/workoutScore";

type RawSet={weight:number;reps:number;partial_reps:number;set_type:string;set_number:number};
type ExerciseSession={exercise_id:string;exercise_name_snapshot:string;position:number;notes:string|null;sets:RawSet[]};
type WorkoutSession={id:string;workout_id:string|null;workout_name_snapshot:string;completed_at:string;notes:string|null};
type ReportWorkout={id:string;name:string;completedAt:string;score:number|null;strengthChange:number|null;skipped:number;techniqueProtected:boolean};
type RangeMode="week"|"lifetime"|"custom";
function normalize(sets:RawSet[]):PerformanceSet[]{return [...sets].sort((a,b)=>a.set_number-b.set_number).filter(s=>["warmup","working","top","backoff"].includes(s.set_type)).map(s=>({weight:Number(s.weight),reps:s.reps,partialReps:s.partial_reps,setType:s.set_type as PerformanceSet["setType"]}));}
function startOfWeek(){const d=new Date();const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));d.setHours(0,0,0,0);return d;}
function endOfWeek(start:Date){const d=new Date(start);d.setDate(d.getDate()+6);d.setHours(23,59,59,999);return d;}
function notes(workout:string|null|undefined,exercise:string|null|undefined){return [workout,exercise].filter(Boolean).join(" ").trim()||null;}
function protectedTechnique(code:string){return ["lower_weight_improved_quality","fewer_reps_improved_quality"].includes(code);}
function localDateInput(d:Date){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function customBoundary(value:string,end=false){const d=new Date(`${value}T00:00:00`);if(end)d.setHours(23,59,59,999);return d;}
function key(value:string){return value.trim().toLowerCase().replace(/\s+/g," ");}
function sameExercise(a:ExerciseSession,b:ExerciseSession){return a.exercise_id===b.exercise_id||key(a.exercise_name_snapshot)===key(b.exercise_name_snapshot);}

export default function ReportsPage(){
 const [mode,setMode]=useState<RangeMode>("week"),[customStart,setCustomStart]=useState(localDateInput(startOfWeek())),[customEnd,setCustomEnd]=useState(localDateInput(new Date()));
 const [workouts,setWorkouts]=useState<ReportWorkout[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{let cancelled=false;const supabase=createSupabaseBrowserClient();async function load(){setLoading(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return;}
 const {data:allSessionData,error:allError}=await supabase.from("workout_sessions").select("id, workout_id, workout_name_snapshot, completed_at, notes").eq("athlete_user_id",user.id).eq("status","completed").order("completed_at",{ascending:true});if(allError){setMessage(allError.message);setLoading(false);return;}const allSessions=(allSessionData??[]) as WorkoutSession[];
 let sessions=allSessions;if(mode==="week"){const start=startOfWeek(),end=endOfWeek(start);sessions=allSessions.filter(s=>{const d=new Date(s.completed_at);return d>=start&&d<=end;});}else if(mode==="custom"){if(!customStart||!customEnd||customStart>customEnd){setMessage("Choose a valid custom date range.");setWorkouts([]);setLoading(false);return;}const start=customBoundary(customStart),end=customBoundary(customEnd,true);sessions=allSessions.filter(s=>{const d=new Date(s.completed_at);return d>=start&&d<=end;});}
 const results:ReportWorkout[]=[];
 for(const session of sessions){const {data:currentData}=await supabase.from("exercise_sessions").select("exercise_id, exercise_name_snapshot, position, notes, sets(weight,reps,partial_reps,set_type,set_number)").eq("workout_session_id",session.id).order("position");const current=(currentData??[]) as ExerciseSession[];const skipped=current.filter(x=>(x.sets??[]).length===0).length;const completed=current.filter(x=>(x.sets??[]).length>0);
 const previousSession=[...allSessions].reverse().find(candidate=>candidate.id!==session.id&&new Date(candidate.completed_at)<new Date(session.completed_at)&&key(candidate.workout_name_snapshot)===key(session.workout_name_snapshot));if(!previousSession){results.push({id:session.id,name:session.workout_name_snapshot,completedAt:session.completed_at,score:null,strengthChange:null,skipped,techniqueProtected:false});continue;}
 const {data:previousData}=await supabase.from("exercise_sessions").select("exercise_id, exercise_name_snapshot, position, notes, sets(weight,reps,partial_reps,set_type,set_number)").eq("workout_session_id",previousSession.id);const previous=(previousData??[]) as ExerciseSession[];const first=[...completed].sort((a,b)=>a.position-b.position)[0];const pf=first?previous.find(x=>sameExercise(first,x)):null;const fs=first?normalize(first.sets).filter(s=>s.setType!=="warmup").slice(0,3):[];const ps=pf?normalize(pf.sets).filter(s=>s.setType!=="warmup").slice(0,3):[];const top=fs.map((s,i)=>scoreExercisePerformance({sets:[s],notes:notes(session.notes,first?.notes)},ps[i]?{sets:[ps[i]],notes:notes(previousSession.notes,pf?.notes)}:null));const rest=completed.filter(x=>x.position!==first?.position).map(x=>{const p=previous.find(y=>sameExercise(x,y));return scoreExercisePerformance({sets:normalize(x.sets),notes:notes(session.notes,x.notes)},p?{sets:normalize(p.sets),notes:notes(previousSession.notes,p.notes)}:null);});const workoutScore=calculateWeightedWorkoutScore(top,rest);
 const currentStrength=completed.map(x=>({exerciseId:key(x.exercise_name_snapshot),sets:x.sets.map(s=>({weight:Number(s.weight),reps:s.reps,setType:s.set_type}))}));const previousStrength=previous.map(x=>({exerciseId:key(x.exercise_name_snapshot),sets:x.sets.map(s=>({weight:Number(s.weight),reps:s.reps,setType:s.set_type}))}));const strength=calculateStrengthChange(currentStrength,previousStrength).percentageChange;results.push({id:session.id,name:session.workout_name_snapshot,completedAt:session.completed_at,score:workoutScore.percentage,strengthChange:strength,skipped,techniqueProtected:top.some(r=>protectedTechnique(r.explanationCode))||rest.some(r=>protectedTechnique(r.explanationCode))});}
 if(!cancelled){setWorkouts(results.reverse());setLoading(false);}}load();return()=>{cancelled=true;};},[mode,customStart,customEnd]);
 const stats=useMemo(()=>{const scored=workouts.filter(w=>w.score!==null),strength=workouts.filter(w=>w.strengthChange!==null);return{avg:scored.length?Math.round(scored.reduce((s,w)=>s+(w.score??0),0)/scored.length):null,avgStrength:strength.length?strength.reduce((s,w)=>s+(w.strengthChange??0),0)/strength.length:null};},[workouts]);
 return <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-6 px-4 py-7 sm:px-6 sm:py-10"><header><p className="text-xs font-black uppercase tracking-[.22em] text-[#ff0032]">PHATBOT History</p><h1 className="mt-2 text-3xl font-black">What did I do?</h1><p className="mt-2 text-zinc-400">Your training log first. Analytics when you want them.</p></header>
 <div className="grid grid-cols-3 gap-2 rounded-xl border border-zinc-900 p-1.5">{([['week','This Week'],['lifetime','Lifetime'],['custom','Custom']] as [RangeMode,string][]).map(([value,label])=><button key={value} onClick={()=>setMode(value)} className={`rounded-lg px-2 py-2 text-xs font-black ${mode===value?'bg-white text-black':'text-zinc-500'}`}>{label}</button>)}</div>
 {mode==="custom"&&<section className="grid grid-cols-2 gap-3 rounded-xl border border-zinc-900 p-4"><label className="text-xs text-zinc-500">Start<input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-800 bg-black px-3 py-2 text-white"/></label><label className="text-xs text-zinc-500">End<input type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-800 bg-black px-3 py-2 text-white"/></label></section>}
 {message&&<p className="rounded-xl border border-zinc-800 p-4 text-sm">{message}</p>}
 {loading?<p className="py-8 text-zinc-400">Building your training log...</p>:<>
 <section className="grid grid-cols-3 gap-3"><div className="rounded-2xl border border-zinc-800 p-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-zinc-500">Workouts</p><p className="mt-2 text-2xl font-black">{workouts.length}</p></div><div className="rounded-2xl border border-zinc-800 p-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-zinc-500">Avg PO</p><p className="mt-2 text-2xl font-black">{stats.avg===null?"—":`${stats.avg}%`}</p></div><div className="rounded-2xl border border-zinc-800 p-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-zinc-500">Strength</p><p className={`mt-2 text-2xl font-black ${stats.avgStrength!==null&&stats.avgStrength>0?'text-[#ff0032]':''}`}>{stats.avgStrength===null?"—":`${stats.avgStrength>=0?"+":""}${stats.avgStrength.toFixed(1)}%`}</p></div></section>
 <section><div className="mb-3"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Workout History</p><h2 className="mt-1 text-xl font-black">Recent training</h2></div><div className="grid gap-3">{workouts.length===0?<div className="rounded-2xl border border-zinc-800 p-5 text-zinc-500">No completed workouts in this range.</div>:workouts.map(w=><Link key={w.id} href={`/sessions/${w.id}/report`} className="rounded-2xl border border-zinc-800 p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="truncate text-lg font-black">{w.name}</p><p className="mt-1 text-xs text-zinc-600">{new Date(w.completedAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</p></div><div className="text-right"><p className="text-xl font-black">{w.score===null?"Base":`${w.score}%`}</p><p className={`mt-1 text-xs font-bold ${w.strengthChange!==null&&w.strengthChange>0?'text-[#ff0032]':'text-zinc-500'}`}>{w.strengthChange===null?"No strength comp":`${w.strengthChange>=0?"+":""}${w.strengthChange.toFixed(1)}% strength`}</p></div></div>{w.skipped>0&&<p className="mt-3 text-xs text-zinc-600">{w.skipped} skipped exercise{w.skipped===1?"":"s"}</p>}<p className="mt-4 text-sm font-black">Open report <span className="text-[#ff0032]">→</span></p></Link>)}</div></section>
 <details className="rounded-2xl border border-zinc-900"><summary className="cursor-pointer list-none p-4 text-sm font-bold text-zinc-500">About these numbers</summary><div className="border-t border-zinc-900 p-4 text-sm leading-6 text-zinc-400"><p>PO score compares completed training against prior comparable performance. Strength change summarizes comparable workout strength. Baseline workouts appear before enough comparison data exists.</p></div></details>
 </>}
 </main>;
}
