"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { scoreExercisePerformance, type PerformanceSet } from "@/features/scoring/progressiveOverload";
import { calculateStrengthChange } from "@/features/scoring/strengthChange";
import { detectPersonalRecords, type PRSet } from "@/features/scoring/personalRecords";

type RawSet={weight:number;reps:number;partial_reps:number;set_type:string;set_number:number};
type Ex={exercise_id:string;exercise_name_snapshot:string;position:number;notes:string|null;sets:RawSet[]};
type ExRow=Ex&{workout_session_id:string};
type Session={id:string;workout_id:string|null;workout_name_snapshot:string;completed_at:string};
type PR={exerciseId:string;exercise:string;message:string};
type Report=Session&{score:number|null;volume:number|null;prs:PR[];needsReview:boolean};
type Plateau={exerciseId:string;exercise:string;recentBest:string;change:number};
type WorkoutTemplate={id:string;name:string;description:string|null;is_active:boolean;created_at:string;sort_order?:number};

const norm=(s:RawSet[]):PerformanceSet[]=>[...s].sort((a,b)=>a.set_number-b.set_number).filter(x=>["warmup","working","top","backoff"].includes(x.set_type)).map(x=>({weight:Number(x.weight),reps:x.reps,partialReps:x.partial_reps,setType:x.set_type as PerformanceSet["setType"]}));
const prs=(s:RawSet[]):PRSet[]=>s.map(x=>({weight:Number(x.weight),reps:x.reps,partialReps:x.partial_reps,setType:x.set_type}));
const weekStart=()=>{const d=new Date(),day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));d.setHours(0,0,0,0);return d;};
const best=(s:RawSet[])=>[...s.filter(x=>x.set_type!=="warmup"&&x.reps>0)].sort((a,b)=>Number(b.weight)-Number(a.weight)||b.reps-a.reps)[0]??null;
const est=(s:RawSet)=>Number(s.weight)*(1+s.reps/30);

export default function CoachAthletePage(){
 const{athleteId}=useParams<{athleteId:string}>();
 const[name,setName]=useState("Athlete"),[unit,setUnit]=useState<"lb"|"kg">("lb"),[reports,setReports]=useState<Report[]>([]),[plateaus,setPlateaus]=useState<Plateau[]>([]),[workouts,setWorkouts]=useState<WorkoutTemplate[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showTemplates,setShowTemplates]=useState(false),[showReports,setShowReports]=useState(false),[working,setWorking]=useState(false);

 useEffect(()=>{let cancelled=false;const supabase=createSupabaseBrowserClient();async function load(){
  setLoading(true);setMessage("");
  const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth/coach";return;}
  const{data:link}=await supabase.from("coach_athletes").select("athlete_user_id,created_at").eq("coach_user_id",user.id).eq("athlete_user_id",athleteId).eq("active",true).maybeSingle();
  if(!link){setMessage("You do not have access to this athlete.");setLoading(false);return;}
  const[{data:p},{data:ap},{data:ss,error},{data:templates},{data:exerciseRows,error:exerciseError},{data:feedback}]=await Promise.all([
   supabase.from("profiles").select("display_name").eq("id",athleteId).maybeSingle(),
   supabase.from("athlete_profiles").select("preferred_unit").eq("user_id",athleteId).maybeSingle(),
   supabase.from("workout_sessions").select("id,workout_id,workout_name_snapshot,completed_at").eq("athlete_user_id",athleteId).eq("status","completed").order("completed_at",{ascending:true}),
   supabase.from("workouts").select("*").eq("athlete_user_id",athleteId),
   supabase.from("exercise_sessions").select("workout_session_id,exercise_id,exercise_name_snapshot,position,notes,sets(weight,reps,partial_reps,set_type,set_number),workout_sessions!inner(athlete_user_id,status)").eq("workout_sessions.athlete_user_id",athleteId).eq("workout_sessions.status","completed"),
   supabase.from("coach_workout_feedback").select("workout_session_id").eq("athlete_user_id",athleteId).eq("coach_user_id",user.id)
  ]);
  if(cancelled)return;
  setName(p?.display_name??"Athlete");setUnit(ap?.preferred_unit==="kg"?"kg":"lb");
  const sortedTemplates=((templates??[]) as WorkoutTemplate[]).sort((a,b)=>(a.is_active===b.is_active?0:a.is_active?-1:1)||((a.sort_order??9999)-(b.sort_order??9999))||(+new Date(a.created_at)-+new Date(b.created_at)));
  setWorkouts(sortedTemplates);
  if(error||exerciseError){setMessage(error?.message??exerciseError?.message??"Unable to load athlete history.");setLoading(false);return;}
  const sessions=(ss??[])as Session[],bySession=new Map<string,Ex[]>();
  for(const row of(exerciseRows??[])as unknown as ExRow[]){const list=bySession.get(row.workout_session_id)??[];list.push({exercise_id:row.exercise_id,exercise_name_snapshot:row.exercise_name_snapshot,position:row.position,notes:row.notes,sets:row.sets??[]});bySession.set(row.workout_session_id,list);}for(const list of bySession.values())list.sort((a,b)=>a.position-b.position);
  const reviewed=new Set((feedback??[]).map(x=>x.workout_session_id));
  const built:Report[]=[],history=new Map<string,{name:string;date:string;sets:RawSet[]}[]>(),prHistory=new Map<string,RawSet[]>(),lastWorkoutById=new Map<string,Session>(),lastWorkoutByName=new Map<string,Session>(),lastExercise=new Map<string,Ex>();
  for(const session of sessions){
   const cur=bySession.get(session.id)??[],sessionPRs:PR[]=[];
   for(const x of cur){const oldSets=prHistory.get(x.exercise_id)??[];for(const pr of detectPersonalRecords(prs(x.sets??[]),prs(oldSets)))sessionPRs.push({exerciseId:x.exercise_id,exercise:x.exercise_name_snapshot,message:pr.message});prHistory.set(x.exercise_id,[...oldSets,...(x.sets??[])]);const a=history.get(x.exercise_id)??[];a.push({name:x.exercise_name_snapshot,date:session.completed_at,sets:x.sets??[]});history.set(x.exercise_id,a);}
   const needsReview=new Date(session.completed_at)>=new Date(link.created_at)&&!reviewed.has(session.id);
   const nameKey=session.workout_name_snapshot.trim().toLowerCase();
   const priorWorkout=(session.workout_id?lastWorkoutById.get(session.workout_id):undefined)??lastWorkoutByName.get(nameKey);
   const sameWorkoutOld=priorWorkout?(bySession.get(priorWorkout.id)??[]):[];
   const priorFor=(exercise:Ex)=>sameWorkoutOld.find(x=>x.exercise_id===exercise.exercise_id)??lastExercise.get(exercise.exercise_id)??null;
   const first=[...cur].sort((a,b)=>a.position-b.position)[0],pf=first?priorFor(first):null,fs=first?norm(first.sets).filter(x=>x.setType!=="warmup").slice(0,3):[],ps=pf?norm(pf.sets).filter(x=>x.setType!=="warmup").slice(0,3):[];
   const top=fs.map((set,i)=>scoreExercisePerformance({sets:[set]},ps[i]?{sets:[ps[i]]}:null)).filter(x=>x.result!=="baseline"),ta=top.length?top.reduce((s,x)=>s+x.score,0)/top.length:null;
   const acc=cur.filter(x=>x.position>1).map(x=>{const q=priorFor(x);return scoreExercisePerformance({sets:norm(x.sets),notes:x.notes},q?{sets:norm(q.sets),notes:q.notes}:null);}).filter(x=>x.result!=="baseline"),aa=acc.length?acc.reduce((s,x)=>s+x.score,0)/acc.length:null,raw=ta===null?aa:aa===null?ta:ta*.6+aa*.4;
   const comparableCurrent=cur.filter(x=>priorFor(x)!==null),comparablePrior=comparableCurrent.map(x=>priorFor(x)!).filter(Boolean);
   const volume=comparableCurrent.length?calculateStrengthChange(comparableCurrent.map(x=>({exerciseId:x.exercise_id,sets:x.sets.map(s=>({weight:Number(s.weight),reps:s.reps,setType:s.set_type}))})),comparablePrior.map(x=>({exerciseId:x.exercise_id,sets:x.sets.map(s=>({weight:Number(s.weight),reps:s.reps,setType:s.set_type}))}))).percentageChange:null;
   built.push({...session,score:raw===null?null:Math.round(raw*100),volume,prs:sessionPRs,needsReview});
   if(session.workout_id)lastWorkoutById.set(session.workout_id,session);lastWorkoutByName.set(nameKey,session);for(const x of cur)lastExercise.set(x.exercise_id,x);
  }
  const pl:Plateau[]=[];for(const[id,h]of history){const r=[...h].sort((a,b)=>+new Date(b.date)-+new Date(a.date)).slice(0,3),bs=r.map(item=>({item,b:best(item.sets)})).filter(x=>x.b)as{item:{name:string;date:string;sets:RawSet[]};b:RawSet}[];if(bs.length<3)continue;const change=est(bs[2].b)>0?(est(bs[0].b)-est(bs[2].b))/est(bs[2].b)*100:0,progress=bs.slice(0,2).some((x,i)=>Number(x.b.weight)>Number(bs[i+1].b.weight)||(Number(x.b.weight)===Number(bs[i+1].b.weight)&&x.b.reps>bs[i+1].b.reps));if(!progress&&change<1)pl.push({exerciseId:id,exercise:bs[0].item.name,recentBest:`${bs[0].b.weight} ${ap?.preferred_unit==="kg"?"kg":"lb"} × ${bs[0].b.reps}`,change});}
  if(cancelled)return;setPlateaus(pl.slice(0,6));setReports(built.reverse());setLoading(false);
 }load();return()=>{cancelled=true;};},[athleteId]);

 async function archiveWorkout(workout:WorkoutTemplate){setWorking(true);setMessage("");const s=createSupabaseBrowserClient();const{error}=await s.from("workouts").update({is_active:!workout.is_active}).eq("id",workout.id).eq("athlete_user_id",athleteId);if(error)setMessage(error.message);else setWorkouts(list=>list.map(w=>w.id===workout.id?{...w,is_active:!w.is_active}:w).sort((a,b)=>(a.is_active===b.is_active?0:a.is_active?-1:1)||((a.sort_order??9999)-(b.sort_order??9999))));setWorking(false);}
 async function deleteWorkout(workout:WorkoutTemplate){if(!window.confirm(`Delete ${workout.name}? Completed workout history will be preserved.`))return;setWorking(true);setMessage("");const s=createSupabaseBrowserClient();const{error}=await s.from("workouts").delete().eq("id",workout.id).eq("athlete_user_id",athleteId);if(error)setMessage(error.message);else setWorkouts(list=>list.filter(w=>w.id!==workout.id));setWorking(false);}
 async function moveWorkout(index:number,direction:-1|1){const active=workouts.filter(w=>w.is_active),target=index+direction;if(target<0||target>=active.length)return;const reordered=[...active],[item]=reordered.splice(index,1);reordered.splice(target,0,item);setWorking(true);setMessage("");const s=createSupabaseBrowserClient();const results=await Promise.all(reordered.map((w,i)=>s.from("workouts").update({sort_order:i+1}).eq("id",w.id).eq("athlete_user_id",athleteId)));const err=results.find(r=>r.error)?.error;if(err){setMessage("Workout reordering needs the new PHATBOT workout-order database update applied in Supabase first.");}else{const archived=workouts.filter(w=>!w.is_active);setWorkouts([...reordered.map((w,i)=>({...w,sort_order:i+1})),...archived]);}setWorking(false);}

 if(loading)return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12">Beep boop... assembling athlete performance hub.</main>;
 const wk=reports.filter(r=>new Date(r.completed_at)>=weekStart()),sc=wk.filter(r=>r.score!==null),score=sc.length?Math.round(sc.reduce((s,r)=>s+(r.score??0),0)/sc.length):null,vr=wk.filter(r=>r.volume!==null),volume=vr.length?vr.reduce((s,r)=>s+(r.volume??0),0)/vr.length:null,weekPRs=wk.reduce((n,r)=>n+r.prs.length,0),needsReview=reports.filter(r=>r.needsReview),recentPRs=reports.flatMap(r=>r.prs.map(p=>({...p,date:r.completed_at}))).slice(0,4),activeWorkouts=workouts.filter(w=>w.is_active),visibleTemplates=showTemplates?workouts:activeWorkouts.slice(0,2);

 return <main className="mx-auto flex min-h-screen max-w-5xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Coach · Athlete Performance Hub</p><h1 className="mt-2 text-3xl font-bold">{name}</h1><p className="mt-2 text-zinc-400">Performance first. Coaching signals next. Programming and history stay one tap away.</p></div><div className="flex flex-wrap gap-2"><Link href={`/coach/athletes/${athleteId}/workouts/new`} className="phat-accent-bg rounded-lg px-4 py-2 text-center text-sm font-semibold">Add Workout</Link><Link href="/coach" className="rounded-lg border border-zinc-700 px-4 py-2 text-center text-sm font-semibold">All Athletes</Link></div></header>
  {message&&<p className="rounded-xl border border-zinc-800 p-4 text-sm">{message}</p>}

  <section><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Performance Metrics</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Workouts This Week" value={String(wk.length)}/><Metric label="Average PHATBOT Score" value={score===null?"Baseline":`${score}%`}/><Metric label="Training Volume vs Prior" value={volume===null?"N/A":`${volume>=0?"+":""}${volume.toFixed(1)}%`} accent={volume!==null&&volume>0}/><Metric label="PRs This Week" value={String(weekPRs)} accent={weekPRs>0}/></div></section>

  <section className={`rounded-2xl border p-5 ${needsReview.length||plateaus.length?"border-[rgba(255,0,50,.45)] bg-[rgba(255,0,50,.05)]":"border-zinc-800"}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Needs Attention</p><h2 className="mt-1 text-xl font-bold">{needsReview.length||plateaus.length?"PHATBOT has coaching signals for you.":"No urgent coaching signals."}</h2><p className="mt-2 text-sm text-zinc-400">{needsReview.length?`${needsReview.length} completed workout${needsReview.length===1?" is":"s are"} waiting for coach review. `:""}{plateaus.length?`${plateaus.length} exercise plateau signal${plateaus.length===1?" is":"s are"} active.`:"Plateau monitoring is currently clear."}</p></div><button onClick={()=>setShowReports(v=>!v)} className={`rounded-lg px-4 py-3 text-sm font-bold ${needsReview.length?"phat-accent-bg":"border border-zinc-700"}`}>{needsReview.length?`Review ${needsReview.length} Workout${needsReview.length===1?"":"s"}`:"Workout Reports"}</button></div>{plateaus.length>0&&<div className="mt-4 grid gap-2 sm:grid-cols-2">{plateaus.slice(0,4).map(p=><Link key={p.exerciseId} href={`/coach/athletes/${athleteId}/trends/exercises?exercise=${encodeURIComponent(p.exerciseId)}`} className="rounded-xl border border-zinc-800 bg-black/30 p-4"><p className="font-semibold">{p.exercise}</p><p className="mt-1 text-xs text-zinc-400">Recent best {p.recentBest} · 3-exposure change {p.change>=0?"+":""}{p.change.toFixed(1)}%</p></Link>)}</div>}</section>

  {showReports&&<section className="rounded-2xl border border-zinc-800 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Workout Reports</h2><p className="mt-1 text-sm text-zinc-500">Newest workouts first. Sessions needing review are highlighted.</p></div><Link href={`/coach/athletes/${athleteId}/reports`} className="text-sm font-bold text-[#ff0032]">Full Reports →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{reports.slice(0,20).map(r=><Link href={`/coach/athletes/${athleteId}/sessions/${r.id}`} key={r.id} className={`rounded-xl border p-4 ${r.needsReview?"border-[#ff0032] bg-[rgba(255,0,50,.05)]":"border-zinc-800"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{r.workout_name_snapshot}</p><p className="mt-1 text-xs text-zinc-500">{new Date(r.completed_at).toLocaleDateString()}</p>{r.needsReview&&<p className="mt-2 text-xs font-bold uppercase tracking-widest text-[#ff0032]">Needs Coach Review</p>}</div><div className="text-right"><p className="font-bold">{r.score===null?"Baseline":`${r.score}%`}</p><p className="text-xs text-zinc-500">Volume {r.volume===null?"N/A":`${r.volume>=0?"+":""}${r.volume.toFixed(1)}%`}</p></div></div></Link>)}</div></section>}

  <section className="grid gap-3 sm:grid-cols-3"><Link href={`/coach/athletes/${athleteId}/reports`} className="rounded-xl border border-zinc-700 p-5 transition hover:border-[#ff0032]"><p className="phat-accent text-xs font-bold uppercase tracking-widest">Reports</p><p className="mt-2 text-lg font-bold">Performance Reports</p><p className="mt-1 text-sm text-zinc-400">This week, lifetime, or a custom reporting window.</p></Link><Link href={`/coach/athletes/${athleteId}/trends/workouts`} className="rounded-xl border border-zinc-700 p-5 transition hover:border-[#ff0032]"><p className="phat-accent text-xs font-bold uppercase tracking-widest">By Workout</p><p className="mt-2 text-lg font-bold">Workout Trends</p><p className="mt-1 text-sm text-zinc-400">Follow the full PO score history for every workout.</p></Link><Link href={`/coach/athletes/${athleteId}/trends/exercises`} className="rounded-xl border border-zinc-700 p-5 transition hover:border-[#ff0032]"><p className="phat-accent text-xs font-bold uppercase tracking-widest">By Exercise</p><p className="mt-2 text-lg font-bold">Exercise Trends</p><p className="mt-1 text-sm text-zinc-400">Drill into PRs, plateaus, and exercise history.</p></Link></section>

  {recentPRs.length>0&&<section><h2 className="mb-3 text-xl font-bold">Recent Wins</h2><div className="grid gap-3 md:grid-cols-2">{recentPRs.map((p,i)=><Link key={`${p.exerciseId}-${i}`} href={`/coach/athletes/${athleteId}/trends/exercises?exercise=${encodeURIComponent(p.exerciseId)}`} className="rounded-xl border border-[rgba(255,0,50,.38)] p-5"><p className="phat-accent text-xs font-bold uppercase tracking-widest">Recent PR</p><p className="mt-2 font-bold">{p.exercise}</p><p className="mt-1 text-sm text-zinc-300">{p.message}</p><p className="mt-2 text-xs text-zinc-500">{new Date(p.date).toLocaleDateString()}</p></Link>)}</div></section>}

  <section className="rounded-2xl border border-zinc-800 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="phat-accent text-xs font-bold uppercase tracking-widest">Programming</p><h2 className="mt-1 text-xl font-bold">Workout Templates</h2><p className="mt-1 text-sm text-zinc-400">Two quick-access templates are shown. Expand to manage the full program.</p></div><div className="flex gap-2"><Link href={`/coach/athletes/${athleteId}/workouts/new`} className="phat-accent-bg rounded-lg px-4 py-2 text-sm font-bold">Add Workout</Link>{workouts.length>2&&<button onClick={()=>setShowTemplates(v=>!v)} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-bold">{showTemplates?"Show Less":"See More"}</button>}</div></div>{visibleTemplates.length===0?<p className="mt-5 rounded-xl border border-dashed border-zinc-700 p-6 text-center text-zinc-400">No workout templates yet.</p>:<div className="mt-4 grid gap-3 sm:grid-cols-2">{visibleTemplates.map((w)=>{const activeIndex=activeWorkouts.findIndex(x=>x.id===w.id);return <article key={w.id} className={`rounded-xl border p-4 ${w.is_active?"border-zinc-800":"border-zinc-900 opacity-60"}`}><div className="flex items-start justify-between gap-3"><Link href={`/coach/athletes/${athleteId}/workouts/${w.id}`} className="min-w-0 flex-1"><p className="font-semibold">{w.name}</p>{w.description&&<p className="mt-1 line-clamp-2 text-sm text-zinc-500">{w.description}</p>}<p className="phat-accent mt-3 text-sm font-semibold">Edit Workout →</p></Link><span className="rounded-full border border-zinc-700 px-2 py-1 text-[10px] font-bold uppercase">{w.is_active?"Active":"Archived"}</span></div>{showTemplates&&<div className="mt-4 flex flex-wrap gap-2 border-t border-zinc-900 pt-3">{w.is_active&&<><button disabled={working||activeIndex<=0} onClick={()=>moveWorkout(activeIndex,-1)} className="rounded border border-zinc-800 px-2 py-1 text-xs disabled:opacity-30">↑ Move</button><button disabled={working||activeIndex<0||activeIndex>=activeWorkouts.length-1} onClick={()=>moveWorkout(activeIndex,1)} className="rounded border border-zinc-800 px-2 py-1 text-xs disabled:opacity-30">↓ Move</button></>}<button disabled={working} onClick={()=>archiveWorkout(w)} className="rounded border border-zinc-800 px-2 py-1 text-xs">{w.is_active?"Archive":"Restore"}</button><button disabled={working} onClick={()=>deleteWorkout(w)} className="rounded border border-red-950 px-2 py-1 text-xs text-red-300">Delete</button></div>}</article>})}</div>}</section>
 </main>;
}

function Metric({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className={`min-w-0 rounded-2xl border p-5 ${accent?"border-[rgba(255,0,50,.42)] bg-[rgba(255,0,50,.06)]":"border-zinc-800"}`}><p className={`text-xs uppercase tracking-widest ${accent?"phat-accent":"text-zinc-500"}`}>{label}</p><p className="mt-2 break-words text-3xl font-black sm:text-4xl">{value}</p></div>}
