"use client";

import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";

type Competition="beast"|"eager_beaver"|"cardio_bunny"|"step_king";
type Period={id:string;competition:Competition;period_end:string;status:"open"|"reconciling"|"finalized"};
type Row={rank:number|null;score:number;result_label:string|null;is_me:boolean;display_name:string};
const order:Competition[]=["beast","eager_beaver","cardio_bunny","step_king"];
const labels:Record<Competition,string>={beast:"Beast",eager_beaver:"Eager Beaver",cardio_bunny:"Cardio Bunny",step_king:"Step King"};
const hardware:Record<Competition,string>={beast:"Beast Medallion",eager_beaver:"Golden Log",cardio_bunny:"Golden Carrot",step_king:"Golden Crown"};
function result(k:Competition,r:Row|null){if(!r)return"Unranked";if(r.result_label)return r.result_label;if(k==="step_king")return `${Math.round(r.score).toLocaleString()} steps`;if(k==="eager_beaver")return `${r.score.toFixed(1)} Eager`;return `${r.score>=0?"+":""}${r.score.toFixed(1)}%`;}
function remaining(end:string){const ms=new Date(end).getTime()-Date.now();if(ms<=0)return"Closing now";const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);if(h>=24){const d=Math.floor(h/24),rh=h%24;return `${d}d ${rh}h remaining`;}return `${h}h ${m}m remaining`;}
export default function ChampionshipSunday(){const[periods,setPeriods]=useState<Period[]>([]),[boards,setBoards]=useState<Record<string,Row[]>>({}),[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);async function load(){const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const{data}=await s.from("competition_periods").select("id,competition,period_end,status").eq("cadence","weekly").in("status",["open","reconciling"]).order("period_start",{ascending:false});const latest=new Map<Competition,Period>();for(const p of (data??[]) as Period[])if(!latest.has(p.competition))latest.set(p.competition,p);const map:Record<string,Row[]>={};await Promise.all([...latest.values()].map(async p=>{const{data:rows}=await s.rpc("competition_leaderboard",{p_period_id:p.id});map[p.competition]=(rows??[]) as Row[]}));setPeriods([...latest.values()]);setBoards(map)}void load();return()=>clearInterval(timer)},[]);
const end=periods[0]?.period_end??null,daysAway=useMemo(()=>end?(new Date(end).getTime()-now)/86400000:99,[end,now]);if(!end)return null;const championshipMode=daysAway<=2.5;return <div className="mx-auto max-w-2xl px-4 pt-7 sm:px-6 sm:pt-10"><section className={`relative overflow-hidden rounded-3xl border p-5 ${championshipMode?"border-yellow-400/50 bg-gradient-to-br from-yellow-500/15 via-zinc-950 to-black":"border-zinc-800 bg-zinc-950"}`}><div className="absolute right-4 top-3 text-yellow-300/20">♛ ✦ 🥕</div><p className={`text-xs font-black uppercase tracking-[.22em] ${championshipMode?"text-yellow-400":"text-zinc-500"}`}>{championshipMode?"Championship Sunday Approaching":"Weekly Hardware Hunt"}</p><div className="mt-2 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">Four trophies. One weekly close.</h2><p className="mt-1 text-sm text-zinc-500">Weekly results lock Sunday at noon ET.</p></div><p className="shrink-0 text-xs font-black uppercase tracking-[.12em] text-yellow-500">{remaining(end)}</p></div><div className="mt-5 grid grid-cols-2 gap-3">{order.map(k=>{const board=boards[k]??[],me=board.find(r=>r.is_me)??null,leader=board.find(r=>r.rank===1)??board[0]??null;return <div key={k} className="rounded-2xl border border-zinc-800 bg-black/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-600">{hardware[k]}</p><p className="mt-1 font-black">{labels[k]}</p></div><p className={`text-xl font-black ${me?.rank===1?"text-yellow-400":"text-white"}`}>{me?.rank?`#${me.rank}`:"—"}</p></div><p className="mt-3 text-sm font-black text-zinc-300">{result(k,me)}</p><p className="mt-1 text-[11px] text-zinc-600">{me?.rank===1?"You currently hold the hardware.":leader?`Leader: ${leader.result_label??result(k,leader)}`:"No eligible leader yet."}</p></div>})}</div>{championshipMode&&<p className="mt-4 text-center text-xs font-bold text-yellow-500">Sunday is for defending leads, stealing hardware, and making PHATBOT recalculate its opinions about humanity.</p>}</section></div>}
