"use client";

import { useMemo, useState } from "react";

type Competition = "beast" | "eager_beaver" | "cardio_bunny" | "step_king";
type Cadence = "daily" | "weekly";
type Props = { competition: Competition; cadence: Cadence; winnerName: string; result: string; isMine?: boolean };
const names:Record<Competition,string>={beast:"BEAST",eager_beaver:"EAGER BEAVER",cardio_bunny:"CARDIO BUNNY",step_king:"STEP KING"};
const hardware:Record<Competition,string>={beast:"BEAST MEDALLION",eager_beaver:"GOLDEN LOG",cardio_bunny:"GOLDEN CARROT",step_king:"GOLDEN CROWN"};
function escapeXml(value:string){return value.replace(/[<>&'\"]/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[char]??char));}
function awardSvg(c:Competition){if(c==="beast")return `<g transform="translate(540 485)"><circle r="162" fill="#f5b800"/><circle r="138" fill="#ffd95a" stroke="#8b5a00" stroke-width="12"/><circle r="112" fill="#f4bd28" stroke="#fff0a6" stroke-width="5"/><text y="-18" text-anchor="middle" font-family="Arial Black,Arial" font-size="42" font-weight="900" fill="#090909">BEAST</text><text y="34" text-anchor="middle" font-family="Arial Black,Arial" font-size="30" font-weight="900" fill="#090909">OF THE ${"${CADENCE}"}</text></g>`;if(c==="step_king")return `<g transform="translate(540 455)" fill="#f6c928" stroke="#ffe88d" stroke-width="8"><path d="M-180 95 L-145 -125 L-45 5 L0 -165 L45 5 L145 -125 L180 95 Z"/><rect x="-172" y="95" width="344" height="70" rx="24"/></g>`;if(c==="cardio_bunny")return `<g transform="translate(540 460)"><path d="M0 -170 C85 -90 110 30 35 175 C15 215 -15 215 -35 175 C-110 30 -85 -90 0 -170 Z" fill="#f5bd22" stroke="#ffe98f" stroke-width="9"/></g>`;return `<g transform="translate(540 470)"><rect x="-170" y="-54" width="340" height="108" rx="54" fill="#d99b13" stroke="#ffe47a" stroke-width="9"/><rect x="-112" y="55" width="224" height="52" rx="18" fill="#f6c432"/></g>`;}
export default function CompetitionShareCard({competition,cadence,winnerName,result,isMine=false}:Props){const[message,setMessage]=useState("");const svg=useMemo(()=>{const period=cadence==="weekly"?"WEEK":"DAY",art=awardSvg(competition).replace("${CADENCE}",period);return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="#050505"/><text x="80" y="105" font-family="Arial Black,Arial" font-size="30" font-weight="900" letter-spacing="8" fill="#ff0032">PHATBOT COMPETE</text><text x="80" y="170" font-family="Arial,Helvetica" font-size="25" font-weight="700" letter-spacing="5" fill="#777">${cadence==="weekly"?"WEEKLY CHAMPION":"DAILY CHAMPION"}</text>${art}<text x="540" y="760" text-anchor="middle" font-family="Arial Black,Arial" font-size="64" font-weight="900" fill="#fff">${names[competition]}</text><text x="540" y="828" text-anchor="middle" font-family="Arial Black,Arial" font-size="34" font-weight="900" fill="#f7c623">${hardware[competition]}</text><text x="540" y="965" text-anchor="middle" font-family="Arial Black,Arial" font-size="62" font-weight="900" fill="#fff">${escapeXml(winnerName)}</text><text x="540" y="1032" text-anchor="middle" font-family="Arial,Helvetica" font-size="36" font-weight="800" fill="#f7c623">${escapeXml(result)}</text><text x="540" y="1184" text-anchor="middle" font-family="Arial Black,Arial" font-size="28" font-weight="900" fill="#fff">TRAIN. TRACK. IMPROVE. COMPETE.</text><text x="540" y="1242" text-anchor="middle" font-family="Arial,Helvetica" font-size="24" font-weight="700" fill="#777">Powered by PHATBOT</text></svg>`},[competition,cadence,winnerName,result]);async function share(){try{const image=new Image(),url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml;charset=utf-8"}));await new Promise<void>((res,rej)=>{image.onload=()=>res();image.onerror=rej;image.src=url});const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext("2d");if(!ctx)throw new Error();ctx.drawImage(image,0,0);URL.revokeObjectURL(url);const blob=await new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error()),"image/png",1));const fileName=`phatbot-${competition}-${cadence}.png`;const href=URL.createObjectURL(blob),a=document.createElement("a");a.href=href;a.download=fileName;a.style.display="none";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),3000);setMessage("Downloaded");}catch(e){if((e as Error)?.name!=="AbortError")setMessage("Try again")}}
return <div className="mt-5 flex flex-col items-center justify-center gap-2"><button type="button" onClick={share} aria-label={isMine?"Download my award image":"Download award image"} title={isMine?"Download my award image":"Download award image"} className="grid h-11 w-11 place-items-center rounded-full border border-yellow-500/40 bg-black/85 text-yellow-300 shadow-lg backdrop-blur hover:border-yellow-400 hover:text-white"><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 17v2a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-2"/></svg></button>{message&&<span className="text-[10px] font-bold uppercase tracking-wider text-zinc-500">{message}</span>}</div>}
