"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";

type Competition="beast"|"eager_beaver"|"cardio_bunny"|"step_king";
type Row={rank:number|null;score:number;result_label:string|null;is_me:boolean};
type Period={id:string;competition:Competition;status:string;period_start:string};
const order:Competition[]=["beast","eager_beaver","cardio_bunny","step_king"];
const hardware:Record<Competition,string>={beast:"Beast Medallion",eager_beaver:"Golden Log",cardio_bunny:"Golden Carrot",step_king:"Golden Crown"};
const icons:Record<Competition,string>={beast:"🏅",eager_beaver:"🪵",cardio_bunny:"🥕",step_king:"👑"};
function easternDay(){return new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"America/New_York"}).format(new Date())}
function result(k:Competition,r:Row|null){if(!r)return"No result yet";if(r.result_label)return r.result_label;if(k==="step_king")return`${Math.round(r.score).toLocaleString()} steps`;if(k==="eager_beaver")return`${r.score.toFixed(1)} Eager`;return`${r.score>=0?"+":""}${r.score.toFixed(1)}%`}
export default function MondayKickoff(){const[rows,setRows]=useState<Record<string,Row|null>>({}),[loading,setLoading]=useState(true);const visible=easternDay()==="Monday";useEffect(()=>{if(!visible){setLoading(false);return}async function load(){const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}const{data:periods}=await s.from("competition_periods").select("id,competition,status,period_start").eq("cadence","weekly").in("status",["open","reconciling"]).order("period_start",{ascending:false});const latest=new Map<string,Period>();for(const p of (periods??[]) as Period[])if(!latest.has(p.competition))latest.set(p.competition,p);const next:Record<string,Row|null>={};await Promise.all(order.map(async k=>{const p=latest.get(k);if(!p){next[k]=null;return}const{data}=await s.rpc("competition_leaderboard",{p_period_id:p.id});next[k]=((data??[]) as Row[]).find(r=>r.is_me)??null}));setRows(next);setLoading(false)}void load()},[visible]);if(!visible)return null;return <div className="mx-auto max-w-2xl px-4 pt-7 sm:px-6 sm:pt-10"><section className="relative overflow-hidden rounded-3xl border border-[#ff0032]/40 bg-gradient-to-br from-[#ff0032]/10 via-zinc-950 to-black p-5"><div className="absolute right-4 top-3 text-[#ff0032]/20">↻ ✦</div><p className="text-xs font-black uppercase tracking-[.22em] text-[#ff0032]">Monday Reset</p><h2 className="mt-2 text-3xl font-black">New week. Empty trophy claims.</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Last week's hardware is locked in the cabinet. The weekly board has reset. PHATBOT is accepting new evidence.</p><div className="mt-5 grid grid-cols-2 gap-2">{order.map(k=>{const me=rows[k]??null;return <div key={k} className="rounded-2xl border border-zinc-800 bg-black/65 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-zinc-600">{hardware[k]}</p><p className="mt-1 text-sm font-black">{loading?"Reading board...":me?.rank?`You are #${me.rank}`:"Open race"}</p></div><span className="text-xl">{icons[k]}</span></div><p className="mt-3 text-xs font-bold text-zinc-500">{loading?"—":result(k,me)}</p></div>})}</div><div className="mt-4 rounded-2xl border border-yellow-500/20 bg-yellow-500/5 px-4 py-3"><p className="text-xs font-black text-yellow-400">THE HUNT STARTS AGAIN</p><p className="mt-1 text-xs leading-5 text-zinc-500">Train, progress, move, and give PHATBOT something inconvenient to calculate.</p></div><Link href="/workouts" className="mt-4 flex w-full items-center justify-center rounded-xl bg-[#ff0032] px-5 py-4 text-sm font-black text-white">Start This Week →</Link></section></div>}
