"use client";

import { useEffect,useState } from "react";
import CompetitionShareCard from "@/components/CompetitionShareCard";

type Competition="beast"|"eager_beaver"|"cardio_bunny"|"step_king"; type Cadence="daily"|"weekly";
type Award={id:string;competition:Competition;cadence:Cadence;period_start:string;result:string|null;score:number|null};
type Props={award:Award|null;athleteName:string;onDismiss:()=>void};
const hardware:Record<Competition,string>={beast:"Beast Medallion",eager_beaver:"Golden Log",cardio_bunny:"Golden Carrot",step_king:"Golden Crown"};
function fmt(k:Competition,s:number){if(k==="step_king")return `${Math.round(s).toLocaleString()} steps`;if(k==="eager_beaver")return `${s.toFixed(1)} Eager`;return `${s>=0?"+":""}${s.toFixed(1)}%`}
function artifact(k:Competition,weekly=false){if(k==="beast")return <div className={`${weekly?"h-40 w-40":"h-36 w-36"} grid place-items-center rounded-full border-[7px] border-yellow-100 bg-gradient-to-br from-white via-yellow-300 to-amber-700 shadow-[0_0_70px_rgba(250,204,21,.45)]`}><span className="text-center text-sm font-black leading-4 text-black">BEAST<br/>OF THE<br/>{weekly?"WEEK":"DAY"}</span></div>;if(k==="cardio_bunny")return <div className="text-9xl drop-shadow-[0_0_40px_rgba(250,204,21,.5)]">🥕</div>;if(k==="step_king")return <div className="text-[10rem] leading-none text-yellow-300 drop-shadow-[0_0_40px_rgba(250,204,21,.5)]">♛</div>;return <div className="relative h-32 w-44 drop-shadow-[0_0_40px_rgba(250,204,21,.5)]"><div className="absolute top-3 h-16 w-44 rounded-full border-4 border-yellow-100 bg-gradient-to-b from-yellow-100 to-amber-600"/><div className="absolute bottom-2 left-6 h-8 w-32 rounded-t bg-yellow-400"/></div>}
export default function NewAwardReveal({award,athleteName,onDismiss}:Props){const[stage,setStage]=useState(0);useEffect(()=>{if(!award)return;setStage(0);const a=setTimeout(()=>setStage(1),250),b=setTimeout(()=>setStage(2),850);return()=>{clearTimeout(a);clearTimeout(b)}},[award]);if(!award)return null;const result=award.result??(award.score!=null?fmt(award.competition,award.score):"Champion");function close(){try{localStorage.setItem(`phatbot-award-revealed:${award!.id}`,"1")}catch{}onDismiss()}return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 px-5 backdrop-blur-md"><div className="absolute inset-0 overflow-hidden pointer-events-none"><div className="absolute left-[10%] top-[12%] text-3xl text-yellow-300/50">✦</div><div className="absolute right-[12%] top-[22%] text-xl text-yellow-300/40">✦</div><div className="absolute bottom-[18%] left-[18%] text-2xl text-yellow-300/30">✦</div><div className="absolute bottom-[28%] right-[15%] text-4xl text-yellow-300/20">✦</div></div><div className={`relative w-full max-w-md text-center transition-all duration-700 ${stage?"translate-y-0 opacity-100":"translate-y-8 opacity-0"}`}><p className="text-xs font-black uppercase tracking-[.34em] text-[#ff0032]">PHATBOT COMPETE</p><p className="mt-4 text-sm font-black uppercase tracking-[.24em] text-yellow-400">{award.cadence==="weekly"?"Legendary Hardware":"Hardware Acquired"}</p><div className={`mt-8 flex justify-center transition-all duration-700 ${stage>=2?"scale-100 opacity-100":"scale-75 opacity-20"}`}>{artifact(award.competition,award.cadence==="weekly")}</div><h1 className="mt-8 text-4xl font-black tracking-tight text-white">YOU WON.</h1><h2 className="mt-2 text-3xl font-black text-yellow-300">{hardware[award.competition]}</h2><p className="mt-5 text-2xl font-black text-white">{result}</p><p className="mt-2 text-sm text-zinc-500">Finalized. Locked. Added to your Trophy Cabinet.</p><div className="relative mx-auto mt-7 h-12 w-12"><CompetitionShareCard competition={award.competition} cadence={award.cadence} winnerName={athleteName||"PHATBOT Athlete"} result={result} isMine/></div><button type="button" onClick={close} className="mt-7 w-full rounded-2xl bg-white px-5 py-4 text-sm font-black text-black">CLAIM HARDWARE →</button><button type="button" onClick={close} className="mt-3 px-5 py-2 text-xs font-bold text-zinc-600">Continue to the arena</button></div></div>}
