"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Session={id:string;completed_at:string}; type Score={workout_session_id:string;score:number|null}; type VolumeRow={workout_session_id:string;sets:{weight:number;reps:number;set_type:string}[]};
function mondayOf(date:Date){const d=new Date(date),day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));d.setHours(0,0,0,0);return d;}
function weekKey(date:Date){return mondayOf(date).toISOString().slice(0,10);}

export default function PhatbotHighlights({athleteUserId}:{athleteUserId:string}){
 const[sessions,setSessions]=useState<Session[]>([]),[scores,setScores]=useState<Score[]>([]),[volumes,setVolumes]=useState<VolumeRow[]>([]);
 useEffect(()=>{let active=true;async function load(){const supabase=createSupabaseBrowserClient(),cutoff=new Date();cutoff.setDate(cutoff.getDate()-28);const{data,error}=await supabase.from("workout_sessions").select("id,completed_at").eq("athlete_user_id",athleteUserId).eq("status","completed").eq("is_test",false).gte("completed_at",cutoff.toISOString()).order("completed_at",{ascending:true});if(error||!active)return;const completed=(data??[])as Session[],ids=completed.map(s=>s.id);if(!ids.length){setSessions([]);return;}const[{data:scoreData},{data:volumeData}]=await Promise.all([supabase.from("workout_scores").select("workout_session_id,score").eq("athlete_user_id",athleteUserId).in("workout_session_id",ids),supabase.from("exercise_sessions").select("workout_session_id,sets(weight,reps,set_type)").in("workout_session_id",ids)]);if(!active)return;setSessions(completed);setScores((scoreData??[])as Score[]);setVolumes((volumeData??[])as VolumeRow[]);}void load();return()=>{active=false;};},[athleteUserId]);
 const highlights=useMemo(()=>{const current=weekKey(new Date()),currentSessions=sessions.filter(s=>weekKey(new Date(s.completed_at))===current),scoreMap=new Map(scores.map(s=>[s.workout_session_id,s.score==null?null:Number(s.score)*100])),currentScores=currentSessions.map(s=>scoreMap.get(s.id)).filter((v):v is number=>v!=null),currentScore=currentScores.length?Math.round(currentScores.reduce((a,b)=>a+b,0)/currentScores.length):null,volumeMap=new Map<string,number>();for(const row of volumes){const v=(row.sets??[]).filter(s=>["working","top","backoff"].includes(s.set_type)).reduce((sum,s)=>sum+(Number(s.weight)||0)*(Number(s.reps)||0),0);volumeMap.set(row.workout_session_id,(volumeMap.get(row.workout_session_id)??0)+v);}const priorMonday=mondayOf(new Date());priorMonday.setDate(priorMonday.getDate()-7);const priorKey=weekKey(priorMonday),priorSessions=sessions.filter(s=>weekKey(new Date(s.completed_at))===priorKey),currentVolume=currentSessions.reduce((sum,s)=>sum+(volumeMap.get(s.id)??0),0),priorVolume=priorSessions.reduce((sum,s)=>sum+(volumeMap.get(s.id)??0),0),volumeChange=currentVolume>0&&priorVolume>0?((currentVolume-priorVolume)/priorVolume)*100:null,items:{label:string;value:string;detail:string}[]=[];if(currentSessions.length)items.push({label:"Training this week",value:String(currentSessions.length),detail:`completed workout${currentSessions.length===1?"":"s"}`});if(currentScore!==null)items.push({label:"PO score",value:`${currentScore}%`,detail:"across scored workouts this week"});if(volumeChange!==null&&volumeChange>0)items.push({label:"Volume win",value:`+${volumeChange.toFixed(0)}%`,detail:"vs last week so far"});return items.slice(0,3);},[sessions,scores,volumes]);
 if(!highlights.length)return null;
 return <section className="flex flex-col gap-3"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff0032]">PHATBOT Highlights</p><h2 className="mt-1 text-xl font-black">What’s going right</h2></div><Link href="/progress" className="text-sm font-black text-zinc-300">See progress →</Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{highlights.map(item=><div key={item.label} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-zinc-500">{item.label}</p><p className="mt-2 text-3xl font-black">{item.value}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{item.detail}</p></div>)}</div></section>;
}
