"use client";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type Room={id:string;room_name:string;join_code:string;status:string};
export default function TrainTogetherCard({sessionId,workoutId,workoutName}:{sessionId:string;workoutId:string|null;workoutName:string}){const[room,setRoom]=useState<Room|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
useEffect(()=>{async function load(){const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const{data}=await (s as any).from("live_workout_rooms").select("id,room_name,join_code,status").eq("host_session_id",sessionId).eq("host_user_id",user.id).eq("status","open").maybeSingle();if(data)setRoom(data)}void load()},[sessionId]);
async function create(){if(busy)return;setBusy(true);setMessage("");try{const s=createSupabaseBrowserClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const roomName=name.trim()||`${workoutName} Crew`;const{data,error}=await (s as any).from("live_workout_rooms").insert({host_user_id:user.id,host_session_id:sessionId,workout_id:workoutId,room_name:roomName}).select("id,room_name,join_code,status").single();if(error)throw error;await (s as any).from("live_workout_room_members").insert({room_id:data.id,athlete_user_id:user.id,workout_session_id:sessionId});setRoom(data);setOpen(false)}catch(e){setMessage((e as Error).message||"PHATBOT could not open the room.")}finally{setBusy(false)}}
const joinUrl=room&&typeof window!=="undefined"?`${window.location.origin}/train-together/${room.join_code}`:"";
async function copy(){if(!joinUrl)return;await navigator.clipboard.writeText(joinUrl);setMessage("Invite link copied.")}
return <section className="mb-5 rounded-3xl border border-[#ff0032]/30 bg-[#ff0032]/5 p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#ff0032]">PHATBOT SOCIAL</p><h2 className="mt-1 text-lg font-black">Train Together</h2><p className="mt-1 text-xs text-zinc-500">Invite the humans around you into this workout.</p></div>{!room&&<button type="button" onClick={()=>setOpen(v=>!v)} className="rounded-xl bg-[#ff0032] px-4 py-2 text-xs font-black text-white">CREATE ROOM</button>}</div>{open&&!room&&<div className="mt-4 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder={`${workoutName} Crew`} className="min-w-0 flex-1 rounded-xl border border-zinc-700 bg-black/20 px-3 py-2 text-sm"/><button disabled={busy} onClick={()=>void create()} className="rounded-xl bg-white px-4 py-2 text-xs font-black text-black">{busy?"OPENING…":"OPEN"}</button></div>}{room&&<div className="mt-4 rounded-2xl border border-zinc-700/60 p-4 text-center"><p className="text-xs font-black uppercase tracking-[.16em] text-zinc-500">{room.room_name}</p><p className="mt-2 font-mono text-3xl font-black tracking-[.18em]">{room.join_code}</p><p className="mt-2 text-xs text-zinc-500">QR is next. For this first pass, share the invite link.</p><button onClick={()=>void copy()} className="mt-3 rounded-xl border border-[#ff0032]/40 px-4 py-2 text-xs font-black text-[#ff0032]">COPY INVITE LINK</button></div>}{message&&<p className="mt-3 text-xs text-zinc-500">{message}</p>}</section>}
