"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import CompetitionShareCard from "@/components/CompetitionShareCard";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Competition="beast"|"eager_beaver"|"cardio_bunny"|"step_king";
type Cadence="daily"|"weekly";
type Period={id:string;competition:Competition;cadence:Cadence;period_start:string;period_end?:string;status:"open"|"reconciling"|"finalized"};
type Row={rank:number|null;athlete_user_id:string;display_name:string;score:number;result_label:string|null;is_me:boolean};
type Award={id:string;period_id:string;award_key:string;awarded_at:string};
type AwardDetail=Award&{competition:Competition;cadence:Cadence;period_start:string;result:string|null;score:number|null};
const labels:Record<Competition,string>={beast:"Beast",eager_beaver:"Eager Beaver",cardio_bunny:"Cardio Bunny",step_king:"Step King"};
const order:Competition[]=["beast","eager_beaver","cardio_bunny","step_king"];
function fmt(k:Competition,s:number){if(k==="step_king")return `${Math.round(s).toLocaleString()} steps`;if(k==="eager_beaver")return `${s.toFixed(1)} Eager`;return `${s>=0?"+":""}${s.toFixed(1)}%`;}
function chase(k:Competition,me:Row|null,l:Row|null){if(!l)return"No eligible result yet. Be the first on the board.";if(!me)return k==="step_king"?`Log valid steps to enter. The lead is ${fmt(k,l.score)}.`:k==="cardio_bunny"?`Complete a comparable cardio effort. The lead is ${fmt(k,l.score)}.`:`Complete an eligible PHATBOT workout. The lead is ${fmt(k,l.score)}.`;if(me.rank===1)return"You're in first. Defend it.";const g=Math.max(0,l.score-me.score);return k==="step_king"?`${Math.ceil(g+1).toLocaleString()} more steps would move you past the current lead.`:k==="eager_beaver"?`Raise your Eager score by more than ${g.toFixed(1)} points to take first.`:`Beat your current result by more than ${g.toFixed(1)} points to take first.`;}
function artifact(k:Competition,weekly=false){if(k==="beast")return <div className={`${weekly?"h-24 w-24":"h-20 w-20"} grid place-items-center rounded-full border-4 border-yellow-300 bg-gradient-to-br from-yellow-100 via-yellow-400 to-amber-700 shadow-[0_0_28px_rgba(250,204,21,.2)]`}><span className="text-center text-[10px] font-black leading-3 text-black">BEAST<br/>{weekly?"OF THE WEEK":"OF THE DAY"}</span></div>;if(k==="cardio_bunny")return <div className="text-6xl">🥕</div>;if(k==="step_king")return <div className="text-7xl text-yellow-400">♛</div>;return <div className="relative h-16 w-24"><div className="absolute top-2 h-9 w-24 rounded-full border-2 border-amber-700 bg-gradient-to-b from-yellow-300 to-amber-600"/><div className="absolute bottom-0 left-4 h-4 w-16 rounded-t bg-yellow-500"/></div>}
function podium(r:number|null){return r===1?"🥇":r===2?"🥈":r===3?"🥉":r?`#${r}`:"—";}
function awardDate(v:string){return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(new Date(v));}
export default function CompetePage(){const[cadence,setCadence]=useState<Cadence>("daily"),[competition,setCompetition]=useState<Competition>("beast"),[periods,setPeriods]=useState<Period[]>([]),[boards,setBoards]=useState<Record<string,Row[]>>({}),[awards,setAwards]=useState<AwardDetail[]>([]),[cabinetOpen,setCabinetOpen]=useState(false),[selectedAward,setSelectedAward]=useState<AwardDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{async function load(){const s=createSupabaseBrowserClient();const{data:{user}}=await s.auth.getUser();if(!user){window.location.href="/auth";return;}const{data:pd,error:pe}=await s.from("competition_periods").select("id,competition,cadence,period_start,period_end,status").in("status",["open","reconciling","finalized"]).order("period_start",{ascending:false});if(pe){setError(pe.message);setLoading(false);return;}const all=(pd??[]) as Period[],latest=new Map<string,Period>();for(const p of all){const key=`${p.competition}:${p.cadence}`;if(!latest.has(key))latest.set(key,p)}const bm:Record<string,Row[]>={};await Promise.all(Array.from(latest.values()).map(async p=>{const{data}=await s.rpc("competition_leaderboard",{p_period_id:p.id});bm[`${p.competition}:${p.cadence}`]=(data??[]) as Row[]}));const{data:ad}=await s.from("competition_awards").select("id,period_id,award_key,awarded_at").eq("athlete_user_id",user.id).order("awarded_at",{ascending:false}).limit(100);const raw=(ad??[]) as Award[],ids=[...new Set(raw.map(a=>a.period_id))];let details:AwardDetail[]=[];if(ids.length){const{data:hist}=await s.from("competition_periods").select("id,competition,cadence,period_start").in("id",ids);const{data:entries}=await s.from("competition_entries").select("period_id,score,result_label").eq("athlete_user_id",user.id).in("period_id",ids);const pm=new Map((hist??[]).map((p:any)=>[p.id,p])),em=new Map((entries??[]).map((e:any)=>[e.period_id,e]));details=raw.map(a=>{const p=pm.get(a.period_id) as any,e=em.get(a.period_id) as any;const rawKey=a.award_key.replace(/_(daily|weekly)$/,""),k=(p?.competition??(order.includes(rawKey as Competition)?rawKey:"beast")) as Competition;return{...a,competition:k,cadence:(p?.cadence??(a.award_key.endsWith("weekly")?"weekly":"daily")) as Cadence,period_start:p?.period_start??a.awarded_at,result:e?.result_label??null,score:e?.score??null}})}setAwards(details);setPeriods(Array.from(latest.values()));setBoards(bm);setLoading(false)}void load()},[]);
const period=periods.find(p=>p.competition===competition&&p.cadence===cadence)??null,board=boards[`${competition}:${cadence}`]??[],me=board.find(r=>r.is_me)??null,leader=board.find(r=>r.rank===1)??board[0]??null,myRank=me?.rank??null,nextMove=useMemo(()=>chase(competition,me,leader),[competition,me,leader]),wonCurrent=!!period&&awards.some(a=>a.period_id===period.id),counts=order.map(k=>({k,count:awards.filter(a=>a.competition===k).length}));
return <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-7 px-4 py-7 sm:px-6 sm:py-10"><header><p className="text-xs font-black uppercase tracking-[.22em] text-[#ff0032]">PHATBOT Compete</p><h1 className="mt-2 text-4xl font-black">Your arena.</h1><p className="mt-2 text-zinc-400">Where you stand, who you're chasing, and what to do next.</p></header>{error&&<p className="rounded-xl border border-[#ff0032]/40 p-4 text-sm">{error}</p>}
{wonCurrent&&<section className="rounded-3xl border border-yellow-400/50 bg-gradient-to-br from-yellow-500/20 via-zinc-950 to-black p-6 text-center"><p className="text-xs font-black uppercase tracking-[.24em] text-yellow-400">Hardware Acquired</p><div className="mt-5 flex justify-center">{artifact(competition,cadence==="weekly")}</div><h2 className="mt-5 text-3xl font-black">You won {labels[competition]}.</h2><p className="mt-2 text-sm text-zinc-400">Finalized. Locked. Yours.</p></section>}
<section className="rounded-3xl border border-[#ff0032]/45 bg-gradient-to-br from-[#ff0032]/10 via-zinc-950 to-black p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff0032]">Your Position</p><h2 className="mt-1 text-4xl font-black">{loading?"—":myRank?`#${myRank}`:"Unranked"}</h2><p className="mt-1 text-sm text-zinc-500">{labels[competition]} · {cadence==="daily"?"Today":"This Week"}{board.length?` · ${board.length} ranked`:""}</p></div>{me&&<div className="text-right"><p className="text-xs font-bold text-zinc-500">YOUR RESULT</p><p className="mt-1 text-xl font-black">{me.result_label??fmt(competition,me.score)}</p></div>}</div><div className="mt-5 rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-4"><p className="text-[10px] font-black uppercase tracking-[.16em] text-yellow-400">Your Next Move</p><p className="mt-2 text-sm font-semibold leading-6">{nextMove}</p></div></section>
<div className="grid grid-cols-2 gap-2 rounded-2xl border border-zinc-800 p-2"><button onClick={()=>setCadence("daily")} className={`rounded-xl py-3 text-sm font-black ${cadence==="daily"?"bg-white text-black":"text-zinc-500"}`}>Daily</button><button onClick={()=>setCadence("weekly")} className={`rounded-xl py-3 text-sm font-black ${cadence==="weekly"?"bg-white text-black":"text-zinc-500"}`}>Weekly</button></div><div className="grid grid-cols-4 gap-2">{order.map(k=><button key={k} onClick={()=>setCompetition(k)} className={`rounded-xl border px-1 py-3 text-[11px] font-black ${competition===k?"border-yellow-500 bg-yellow-500/10 text-yellow-400":"border-zinc-800 text-zinc-500"}`}>{labels[k]}</button>)}</div>
<section><div className="mb-3 flex justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-zinc-500">Live Leaderboard</p><h2 className="mt-1 text-2xl font-black">{labels[competition]}</h2></div><p className="text-xs text-zinc-600">{period?.status??"waiting"}</p></div>{loading?<div className="rounded-2xl border border-zinc-800 p-5 text-zinc-500">Reading the arena...</div>:board.length===0?<div className="rounded-2xl border border-zinc-800 p-5"><p className="font-black">No eligible athletes yet.</p></div>:<div className="overflow-hidden rounded-2xl border border-zinc-800">{board.slice(0,10).map(r=><div key={r.athlete_user_id} className={`grid grid-cols-[54px_1fr_auto] items-center gap-3 border-b border-zinc-900 px-4 py-4 last:border-0 ${r.is_me?"bg-[#ff0032]/8":""}`}><div className="text-center text-lg font-black">{podium(r.rank)}</div><div><p className={`font-black ${r.is_me?"text-[#ff0032]":""}`}>{r.display_name}{r.is_me?" · YOU":""}</p><p className="mt-1 text-xs text-zinc-600">{r.result_label??fmt(competition,r.score)}</p></div><p className="text-sm font-black text-zinc-400">{fmt(competition,r.score)}</p></div>)}</div>}</section>
{leader&&<section className="rounded-3xl border border-yellow-500/35 bg-gradient-to-br from-yellow-500/10 via-zinc-950 to-black p-6 text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-yellow-400">{period?.status==="finalized"?"Official Winner":"Current Leader"}</p><div className="mt-5 flex justify-center">{artifact(competition,cadence==="weekly")}</div><h2 className="mt-4 text-3xl font-black">{leader.display_name}</h2><p className="mt-2 text-lg font-black text-yellow-400">{leader.result_label??fmt(competition,leader.score)}</p><p className="mt-2 text-sm text-zinc-500">{period?.status==="finalized"?"The result is locked. Hardware awarded.":"Live result. The board can still move."}</p></section>}
{leader&&period?.status==="finalized"&&<CompetitionShareCard competition={competition} cadence={cadence} winnerName={leader.display_name} result={leader.result_label??fmt(competition,leader.score)} isMine={leader.is_me}/>} 
<section className="rounded-3xl border border-zinc-800 bg-zinc-950 p-5"><button type="button" onClick={()=>setCabinetOpen(v=>!v)} className="w-full text-left"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-500">Your Trophy Cabinet</p><h2 className="mt-1 text-3xl font-black">{awards.length} {awards.length===1?"piece of hardware":"pieces of hardware"}</h2><p className="mt-2 text-sm text-zinc-500">{cabinetOpen?"Hide the collection":"Open the cabinet →"}</p></div><span className="text-3xl">🏆</span></div></button>{awards.length>0&&<div className="mt-5 grid grid-cols-4 gap-2">{counts.map(({k,count})=><div key={k} className="rounded-xl border border-zinc-800 bg-black px-2 py-3 text-center"><p className="text-lg font-black text-yellow-400">{count}</p><p className="mt-1 text-[9px] font-black uppercase text-zinc-600">{labels[k]}</p></div>)}</div>}{cabinetOpen&&(awards.length===0?<p className="mt-5 text-sm leading-6 text-zinc-500">Empty cabinet. For now. Finalized wins will collect here automatically.</p>:<div className="mt-5 space-y-3">{awards.map(a=><button key={a.id} type="button" onClick={()=>setSelectedAward(a)} className="grid w-full grid-cols-[86px_1fr_auto] items-center gap-3 rounded-2xl border border-yellow-500/20 bg-black p-3 text-left"><div className="flex h-20 items-center justify-center scale-75">{artifact(a.competition,a.cadence==="weekly")}</div><div><p className="font-black">{labels[a.competition]}</p><p className="mt-1 text-xs font-bold uppercase tracking-[.12em] text-yellow-500">{a.cadence==="weekly"?"Weekly Champion":"Daily Champion"}</p><p className="mt-1 text-xs text-zinc-600">{awardDate(a.period_start)}</p></div><div className="text-right"><p className="text-sm font-black text-zinc-300">{a.result??(a.score!=null?fmt(a.competition,a.score):"WIN")}</p><p className="mt-2 text-lg text-zinc-600">›</p></div></button>)}</div>)}</section>
{selectedAward&&<section className="rounded-3xl border border-yellow-400/45 bg-gradient-to-br from-yellow-500/15 via-zinc-950 to-black p-6 text-center"><button type="button" onClick={()=>setSelectedAward(null)} className="float-right rounded-full border border-zinc-700 px-3 py-1 text-sm text-zinc-400">×</button><p className="clear-both text-xs font-black uppercase tracking-[.22em] text-yellow-400">From The Trophy Cabinet</p><div className="mt-5 flex justify-center">{artifact(selectedAward.competition,selectedAward.cadence==="weekly")}</div><h2 className="mt-5 text-3xl font-black">{labels[selectedAward.competition]}</h2><p className="mt-2 text-sm font-black uppercase tracking-[.14em] text-yellow-500">{selectedAward.cadence==="weekly"?"Weekly Champion":"Daily Champion"} · {awardDate(selectedAward.period_start)}</p><p className="mt-3 text-xl font-black">{selectedAward.result??(selectedAward.score!=null?fmt(selectedAward.competition,selectedAward.score):"Hardware acquired")}</p><div className="mt-5"><CompetitionShareCard competition={selectedAward.competition} cadence={selectedAward.cadence} winnerName="PHATBOT Athlete" result={selectedAward.result??(selectedAward.score!=null?fmt(selectedAward.competition,selectedAward.score):"Champion")} isMine/></div></section>}
<section className="rounded-3xl border border-[#ff0032]/40 bg-[#ff0032]/5 p-5"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff0032]">Build Your Case</p><h2 className="mt-2 text-2xl font-black">Want hardware? Give PHATBOT data.</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Completed workouts, comparable cardio, and synced steps create eligible competition results.</p><Link href="/workouts" className="mt-4 flex w-full items-center justify-center rounded-xl bg-[#ff0032] px-5 py-4 font-black text-white">PHATBOT Train →</Link></section><p className="pb-2 text-center text-[11px] text-zinc-700">Live boards are provisional until finalization. Tied leaders share first place and each earn the award.</p></main>}
