"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type DailyMetric = { metric_date: string; steps: number | null; active_energy_kcal: number | null };
type CardioActivity = { id: string; activity_name: string | null; activity_type: number; started_at: string; duration_seconds: number; distance_meters: number | null; active_energy_kcal: number | null; average_heart_rate_bpm: number | null };
type Comparison = { prior: CardioActivity; status: "better" | "same" | "mixed"; message: string };
type Benchmark = { key: string; label: string; activity: CardioActivity; efforts: CardioActivity[]; best: CardioActivity; previous: CardioActivity | null };
const MILE_METERS = 1609.344;
function miles(meters: number | null) { return meters == null ? null : meters / MILE_METERS; }
function duration(seconds: number) { const mins = Math.round(seconds / 60); const h = Math.floor(mins / 60); const m = mins % 60; return h ? `${h}h ${m}m` : `${m} min`; }
function clock(seconds: number) { const total = Math.max(0, Math.round(seconds)); const h = Math.floor(total / 3600), m = Math.floor((total % 3600) / 60), s = total % 60; return h ? `${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}` : `${m}:${String(s).padStart(2,"0")}`; }
function paceSeconds(seconds: number, meters: number | null) { const mi = miles(meters); return !mi || mi <= 0 ? null : seconds / mi; }
function pace(seconds: number, meters: number | null) { const value = paceSeconds(seconds, meters); if (value == null) return null; const mins = Math.floor(value / 60), secs = Math.round(value % 60); return `${mins}:${String(secs).padStart(2, "0")}/mi`; }
function speedMph(seconds: number, meters: number | null) { const mi = miles(meters); return !mi || seconds <= 0 ? null : mi / (seconds / 3600); }
function fmtDate(value: string) { return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function normalizedName(activity: CardioActivity) { return (activity.activity_name ?? "Workout").trim().toLowerCase(); }
function isRun(activity: CardioActivity) { const name = normalizedName(activity); return name === "run" || name.includes("running"); }
function isCycling(activity: CardioActivity) { const name = normalizedName(activity); return name.includes("bike") || name.includes("cycling"); }
function isPerformanceCardio(activity: CardioActivity) { const name = normalizedName(activity); return isRun(activity) || isCycling(activity) || name === "rowing" || name === "swim" || name === "swimming"; }
function isCardioActivity(activity: CardioActivity) { const name = normalizedName(activity); return ["run","running","walk","walking","bike ride","cycling","hike","rowing","swim","swimming","elliptical","stair climbing","mixed cardio","hiit"].some((label) => name.includes(label)); }
function localDayKey(date: Date) { const y = date.getFullYear(), m = String(date.getMonth() + 1).padStart(2,"0"), d = String(date.getDate()).padStart(2,"0"); return `${y}-${m}-${d}`; }
function sevenDayStartKey() { const start = new Date(); start.setHours(0,0,0,0); start.setDate(start.getDate() - 6); return localDayKey(start); }
function sevenDayStartTime() { const start = new Date(); start.setHours(0,0,0,0); start.setDate(start.getDate() - 6); return start.getTime(); }
function distanceWithin(activity: CardioActivity, targetMeters: number, tolerance = 0.05) { return activity.distance_meters != null && Math.abs(activity.distance_meters - targetMeters) / targetMeters <= tolerance; }
function benchmarkKey(activity: CardioActivity) { if (!activity.distance_meters || !isPerformanceCardio(activity)) return null; if (isRun(activity)) { if (distanceWithin(activity, 5000, 0.04)) return { key: "run-5k", label: "5K Run" }; if (distanceWithin(activity, MILE_METERS, 0.04)) return { key: "run-1mi", label: "1 Mile Run" }; if (distanceWithin(activity, 10000, 0.04)) return { key: "run-10k", label: "10K Run" }; } const mi = miles(activity.distance_meters); if (!mi) return null; const rounded = Math.max(1, Math.round(mi)); if (Math.abs(mi - rounded) / rounded <= 0.05) return { key: `${activity.activity_type}-${rounded}mi`, label: `${rounded} Mile ${activity.activity_name ?? "Workout"}` }; return null; }
function comparable(a: CardioActivity, b: CardioActivity) { if (!isPerformanceCardio(a) || a.activity_type !== b.activity_type || !a.distance_meters || !b.distance_meters) return false; const delta = Math.abs(a.distance_meters - b.distance_meters) / b.distance_meters; return delta <= 0.05; }
function comparisonFor(activity: CardioActivity, older: CardioActivity[]): Comparison | null {
  const prior = older.find((candidate) => comparable(activity, candidate)); if (!prior) return null;
  const currentPace = paceSeconds(Number(activity.duration_seconds), activity.distance_meters), priorPace = paceSeconds(Number(prior.duration_seconds), prior.distance_meters); if (currentPace == null || priorPace == null) return null;
  const paceDelta = priorPace - currentPace; const pacePct = Math.abs(paceDelta) / priorPace; const currentHr = activity.average_heart_rate_bpm == null ? null : Number(activity.average_heart_rate_bpm), priorHr = prior.average_heart_rate_bpm == null ? null : Number(prior.average_heart_rate_bpm); const hrDelta = currentHr != null && priorHr != null ? priorHr - currentHr : null;
  const metricLabel = isCycling(activity) ? "speed" : "pace";
  if (pacePct >= 0.01 && paceDelta > 0) return { prior, status: "better", message: `Gains detected. ${metricLabel === "speed" ? "Average speed improved" : `Pace improved by ${clock(paceDelta)} per mile`} versus your comparable ${fmtDate(prior.started_at)} effort.${hrDelta != null && hrDelta > 1 ? ` Average heart rate was also ${Math.round(hrDelta)} bpm lower.` : ""}` };
  if (pacePct <= 0.01 && hrDelta != null && hrDelta >= 3) return { prior, status: "better", message: `Efficiency win. ${metricLabel === "speed" ? "Speed" : "Pace"} was essentially the same, but average heart rate was ${Math.round(hrDelta)} bpm lower than your comparable ${fmtDate(prior.started_at)} effort.` };
  if (pacePct <= 0.01) return { prior, status: "same", message: `Comparable effort detected. ${metricLabel === "speed" ? "Speed" : "Pace"} was essentially unchanged from ${fmtDate(prior.started_at)}. PHATBOT is logging this as a steady performance signal.` };
  return { prior, status: "mixed", message: `Comparable effort detected. This performance was below your ${fmtDate(prior.started_at)} comparable effort. Logged for trend context—not every session needs to be a performance test.` };
}
function buildBenchmarks(activities: CardioActivity[]): Benchmark[] { const groups = new Map<string, { label: string; efforts: CardioActivity[] }>(); for (const activity of activities) { const bucket = benchmarkKey(activity); if (!bucket) continue; const existing = groups.get(bucket.key) ?? { label: bucket.label, efforts: [] }; existing.efforts.push(activity); groups.set(bucket.key, existing); } return Array.from(groups.entries()).map(([key, group]) => { const efforts = [...group.efforts].sort((a,b) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime()); const best = [...efforts].sort((a,b) => Number(a.duration_seconds) - Number(b.duration_seconds))[0]; return { key, label: group.label, activity: efforts[0], efforts, best, previous: efforts[1] ?? null }; }).sort((a,b) => new Date(b.activity.started_at).getTime() - new Date(a.activity.started_at).getTime()); }
function benchmarkTrend(benchmark: Benchmark) { const latest = benchmark.activity, previous = benchmark.previous; if (!previous) return "Baseline established. PHATBOT will compare your next matching effort to this one."; const timeDelta = Number(previous.duration_seconds) - Number(latest.duration_seconds); const latestHr = latest.average_heart_rate_bpm == null ? null : Number(latest.average_heart_rate_bpm), priorHr = previous.average_heart_rate_bpm == null ? null : Number(previous.average_heart_rate_bpm); if (timeDelta > 3) return `Latest effort was ${clock(timeDelta)} faster than the previous ${benchmark.label}.${latestHr != null && priorHr != null && latestHr < priorHr - 1 ? ` Average heart rate was also ${Math.round(priorHr - latestHr)} bpm lower.` : ""}`; if (Math.abs(timeDelta) <= 3 && latestHr != null && priorHr != null && latestHr <= priorHr - 3) return `Time was essentially unchanged, but average heart rate improved by ${Math.round(priorHr - latestHr)} bpm. Efficiency win.`; if (Math.abs(timeDelta) <= 3) return `Latest ${benchmark.label} was essentially steady versus the previous effort.`; return `Latest effort was ${clock(Math.abs(timeDelta))} slower than the previous ${benchmark.label}. PHATBOT will keep this in context as more efforts are collected.`; }

export default function ActivityProgressPage() {
  const [days, setDays] = useState<DailyMetric[]>([]), [activities, setActivities] = useState<CardioActivity[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null);
  useEffect(() => { async function load() { const supabase = createSupabaseBrowserClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.href = "/auth"; return; } const [dailyResult, cardioResult] = await Promise.all([supabase.from("health_daily_metrics").select("metric_date,steps,active_energy_kcal").eq("athlete_user_id", user.id).order("metric_date", { ascending: false }).limit(30), supabase.from("cardio_activities").select("id,activity_name,activity_type,started_at,duration_seconds,distance_meters,active_energy_kcal,average_heart_rate_bpm").eq("athlete_user_id", user.id).order("started_at", { ascending: false }).limit(120)]); if (dailyResult.error || cardioResult.error) setError(dailyResult.error?.message ?? cardioResult.error?.message ?? "Could not load activity history."); setDays((dailyResult.data ?? []) as DailyMetric[]); setActivities((cardioResult.data ?? []) as CardioActivity[]); setLoading(false); } void load(); }, []);
  const summary = useMemo(() => { const dayStart = sevenDayStartKey(), recent = days.filter((d) => d.metric_date >= dayStart && d.metric_date <= localDayKey(new Date())), stepDays = recent.filter((d) => d.steps != null), avgSteps = stepDays.length ? Math.round(stepDays.reduce((sum, d) => sum + Number(d.steps ?? 0), 0) / stepDays.length) : null, totalActive = recent.reduce((sum, d) => sum + Number(d.active_energy_kcal ?? 0), 0), activity7 = activities.filter((a) => new Date(a.started_at).getTime() >= sevenDayStartTime()), cardio7 = activity7.filter(isCardioActivity), cardioMinutes = Math.round(cardio7.reduce((sum, a) => sum + Number(a.duration_seconds), 0) / 60); return { avgSteps, totalActive: Math.round(totalActive), cardioCount: cardio7.length, cardioMinutes }; }, [days, activities]);
  const comparisons = useMemo(() => new Map(activities.map((activity, index) => [activity.id, comparisonFor(activity, activities.slice(index + 1))])), [activities]);
  const benchmarks = useMemo(() => buildBenchmarks(activities), [activities]);
  const latestWin = activities.map((a) => ({ activity: a, comparison: comparisons.get(a.id) })).find((x) => x.comparison?.status === "better");
  if (loading) return <main className="mx-auto min-h-screen max-w-3xl px-6 py-12 text-zinc-300">Beep boop... loading activity history.</main>;
  return <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10">
    <header><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Activity</p><h1 className="mt-2 text-3xl font-bold">Activity & workout history</h1><p className="mt-2 text-zinc-400">Apple Health steps, active energy, walks, runs, rides, strength sessions, and other tracked workouts collected by PHATBOT.</p></header>
    {error && <p className="rounded-xl border border-[#ff0032]/40 bg-[#ff0032]/5 p-4 text-sm">{error}</p>}
    {latestWin?.comparison && <section className="phat-signal rounded-2xl border p-5"><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Cardio Win Detected</p><h2 className="mt-2 text-xl font-bold">{benchmarkKey(latestWin.activity)?.label ?? latestWin.activity.activity_name ?? "Workout"}</h2><p className="mt-3 text-base font-semibold leading-7">Beep boop. {latestWin.comparison.message}</p></section>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">7-day avg steps</p><p className="mt-2 text-2xl font-black">{summary.avgSteps?.toLocaleString() ?? "—"}</p></div><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">7-day active kcal</p><p className="mt-2 text-2xl font-black">{summary.totalActive.toLocaleString()}</p></div><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">7-day cardio</p><p className="mt-2 text-2xl font-black">{summary.cardioCount}</p></div><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">Cardio minutes</p><p className="mt-2 text-2xl font-black">{summary.cardioMinutes}</p></div></section>
    {benchmarks.length > 0 && <section className="rounded-2xl border border-zinc-800 p-5"><div><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Cardio Benchmarks</p><h2 className="mt-1 text-xl font-bold">Comparable efforts</h2><p className="mt-1 text-sm text-zinc-500">PHATBOT recognizes repeatable distances like 1 mile, 5K and 10K runs and tracks time plus heart-rate efficiency.</p></div><div className="mt-4 grid gap-3">{benchmarks.slice(0,6).map((benchmark) => { const latestPace = pace(Number(benchmark.activity.duration_seconds), benchmark.activity.distance_meters), bestPace = pace(Number(benchmark.best.duration_seconds), benchmark.best.distance_meters); return <article key={benchmark.key} className="rounded-xl border border-zinc-800 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-lg font-black">{benchmark.label}</p><p className="mt-1 text-xs text-zinc-500">{benchmark.efforts.length} tracked effort{benchmark.efforts.length === 1 ? "" : "s"} · latest {fmtDate(benchmark.activity.started_at)}</p></div><div className="text-right"><p className="text-xs text-zinc-500">Best time</p><p className="font-black">{clock(Number(benchmark.best.duration_seconds))}</p></div></div><div className="mt-4 grid grid-cols-3 gap-3"><div><p className="text-xs text-zinc-500">Latest time</p><p className="mt-1 font-semibold">{clock(Number(benchmark.activity.duration_seconds))}</p></div><div><p className="text-xs text-zinc-500">Latest pace</p><p className="mt-1 font-semibold">{latestPace ?? "—"}</p></div><div><p className="text-xs text-zinc-500">Avg HR</p><p className="mt-1 font-semibold">{benchmark.activity.average_heart_rate_bpm == null ? "—" : `${Math.round(Number(benchmark.activity.average_heart_rate_bpm))} bpm`}</p></div></div><p className="mt-3 text-sm leading-6 text-zinc-300">Beep boop. {benchmarkTrend(benchmark)}</p>{benchmark.best.id !== benchmark.activity.id && <p className="mt-2 text-xs text-zinc-500">Best pace: {bestPace ?? "—"} on {fmtDate(benchmark.best.started_at)}</p>}</article>; })}</div></section>}
    <section className="rounded-2xl border border-zinc-800 p-5"><div><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Daily Activity</p><h2 className="mt-1 text-xl font-bold">Steps & active energy</h2></div><div className="mt-4 flex flex-col gap-2">{days.length === 0 && <p className="text-sm text-zinc-500">No daily Apple Health history has been synced yet.</p>}{days.slice(0, 14).map((day) => <div key={day.metric_date} className="flex items-center justify-between rounded-xl border border-zinc-900 px-4 py-3"><p className="font-semibold">{fmtDate(`${day.metric_date}T12:00:00`)}</p><div className="text-right"><p className="font-bold">{day.steps == null ? "—" : `${Number(day.steps).toLocaleString()} steps`}</p><p className="text-xs text-zinc-500">{day.active_energy_kcal == null ? "—" : `${Math.round(Number(day.active_energy_kcal))} active kcal`}</p></div></div>)}</div></section>
    <section className="rounded-2xl border border-zinc-800 p-5"><div><p className="phat-accent text-xs font-bold uppercase tracking-[.2em]">Workout Log</p><h2 className="mt-1 text-xl font-bold">Recent tracked workouts</h2><p className="mt-1 text-sm text-zinc-500">Runs, rides, rowing, and swims can receive comparable-effort signals when distance is within 5%. Walks and strength sessions are logged without forcing a performance judgment.</p></div><div className="mt-4 flex flex-col gap-3">{activities.length === 0 && <p className="text-sm text-zinc-500">No Apple Health workouts have been synced yet.</p>}{activities.map((activity) => { const mi = miles(activity.distance_meters), cycling = isCycling(activity), workoutPace = cycling ? null : pace(Number(activity.duration_seconds), activity.distance_meters), workoutSpeed = cycling ? speedMph(Number(activity.duration_seconds), activity.distance_meters) : null, comparison = comparisons.get(activity.id), bucket = benchmarkKey(activity); return <article key={activity.id} className="rounded-xl border border-zinc-800 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-lg font-bold">{bucket?.label ?? activity.activity_name ?? "Workout"}</p><p className="mt-1 text-xs text-zinc-500">{fmtDate(activity.started_at)}{bucket ? ` · ${activity.activity_name ?? "Workout"}` : ""}</p></div><p className="font-bold">{duration(Number(activity.duration_seconds))}</p></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-zinc-500">Distance</p><p className="mt-1 font-semibold">{mi == null ? "—" : `${mi.toFixed(2)} mi`}</p></div><div><p className="text-xs text-zinc-500">{cycling ? "Avg speed" : "Pace"}</p><p className="mt-1 font-semibold">{cycling ? (workoutSpeed == null ? "—" : `${workoutSpeed.toFixed(1)} mph`) : (workoutPace ?? "—")}</p></div><div><p className="text-xs text-zinc-500">Avg HR</p><p className="mt-1 font-semibold">{activity.average_heart_rate_bpm == null ? "—" : `${Math.round(Number(activity.average_heart_rate_bpm))} bpm`}</p></div><div><p className="text-xs text-zinc-500">Active kcal</p><p className="mt-1 font-semibold">{activity.active_energy_kcal == null ? "—" : Math.round(Number(activity.active_energy_kcal))}</p></div></div>{comparison && <div className={`mt-4 rounded-lg border p-3 text-sm leading-6 ${comparison.status === "better" ? "border-[#ff0032]/40 bg-[#ff0032]/5" : "border-zinc-800 bg-zinc-950"}`}><p className="text-xs font-black uppercase tracking-[.16em] text-zinc-500">{comparison.status === "better" ? "Improvement" : comparison.status === "same" ? "Steady" : "Context"}</p><p className="mt-1 text-zinc-300">{comparison.message}</p></div>}</article>; })}</div></section>
    <div className="grid gap-3 sm:grid-cols-2"><Link href="/progress" className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Back to Progress</Link><Link href="/" className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Dashboard</Link></div>
  </main>;
}
