"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

export default function InviteAthletePage(){
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[sending,setSending]=useState(false),[success,setSuccess]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setSending(true);setMessage("");setSuccess(false);const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth/coach";return;}const{data,error}=await supabase.rpc("invite_athlete_by_email",{p_athlete_email:email,p_athlete_name:name||null});if(error){setMessage(error.message);setSending(false);return;}const result=(data??{}) as {status?:string};setSuccess(true);if(result.status==="linked")setMessage("Athlete found. They are now linked to your PHATBOT coach dashboard.");else setMessage("Invitation created. The athlete can create their PHATBOT account with this email and will automatically connect to you.");setSending(false);}
 return <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10"><header><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Coach</p><h1 className="mt-2 text-3xl font-bold">Invite Athlete</h1><p className="mt-2 text-zinc-400">Start the client relationship from Coach View. Existing PHATBOT athletes link immediately. New athletes can sign up using the invited email.</p></header><form onSubmit={submit} className="flex flex-col gap-4 rounded-2xl border border-zinc-800 p-6"><label className="text-sm font-semibold">Athlete name <span className="font-normal text-zinc-500">(optional)</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-black px-4 py-3" placeholder="Jane Athlete"/></label><label className="text-sm font-semibold">Athlete email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-black px-4 py-3" placeholder="athlete@example.com"/></label><button disabled={sending} className="phat-accent-bg rounded-lg px-5 py-3 font-bold disabled:opacity-50">{sending?"Beep boop... inviting":"Invite Athlete"}</button></form>{message&&<section className={`rounded-xl border p-4 ${success?"border-[rgba(255,0,50,.42)] bg-[rgba(255,0,50,.06)]":"border-zinc-800"}`}><p className="font-semibold">{message}</p>{success&&<p className="mt-2 text-sm text-zinc-400">For this MVP test, have the athlete sign in or create an account with the exact email above.</p>}</section>}<Link href="/coach" className="rounded-lg border border-zinc-700 px-5 py-3 text-center font-semibold">Back to Coach Dashboard</Link></main>;
}
