"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import * as XLSX from "xlsx";
import {createSupabaseBrowserClient} from "@/lib/supabase";
import {parseTemplateRows,type TemplateWorkout} from "@/features/import/workoutTemplate";

type Athlete={id:string;name:string};
type ImportResult={created:number;updated:number}|null;

export default function CoachWorkoutImportPage(){
  const[loading,setLoading]=useState(true),[athletes,setAthletes]=useState<Athlete[]>([]),[athleteId,setAthleteId]=useState(""),[fileName,setFileName]=useState(""),[workouts,setWorkouts]=useState<TemplateWorkout[]>([]),[message,setMessage]=useState(""),[parsing,setParsing]=useState(false),[importing,setImporting]=useState(false),[result,setResult]=useState<ImportResult>(null);

  useEffect(()=>{const s=createSupabaseBrowserClient();(async()=>{const{data:{user}}=await s.auth.getUser();if(!user){location.href="/auth";return}const{data:coach}=await s.from("coach_profiles").select("user_id").eq("user_id",user.id).maybeSingle();if(!coach){setMessage("Coach mode is required to import workout templates.");setLoading(false);return}const{data:links,error}=await s.from("coach_athletes").select("athlete_user_id").eq("coach_user_id",user.id).eq("active",true);if(error){setMessage(error.message);setLoading(false);return}const rows:Athlete[]=[];for(const link of links??[]){const{data:p}=await s.from("profiles").select("display_name").eq("id",link.athlete_user_id).maybeSingle();rows.push({id:link.athlete_user_id,name:p?.display_name??"Athlete"})}rows.sort((a,b)=>a.name.localeCompare(b.name));setAthletes(rows);if(rows.length===1)setAthleteId(rows[0].id);setLoading(false)})()},[]);

  async function parseFile(file:File|null){setWorkouts([]);setResult(null);setMessage("");setFileName("");if(!file)return;if(!/\.xlsx$/i.test(file.name)){setMessage("Please choose an .xlsx workout spreadsheet.");return}setParsing(true);setFileName(file.name);try{const buffer=await file.arrayBuffer(),book=XLSX.read(buffer,{type:"array"}),parsed:TemplateWorkout[]=[];for(const sheetName of book.SheetNames){const rows=XLSX.utils.sheet_to_json<unknown[]>(book.Sheets[sheetName],{header:1,raw:false,defval:""});const workout=parseTemplateRows(sheetName,rows);if(workout)parsed.push(workout)}if(!parsed.length)setMessage("PHATBOT could not find workout tabs with Exercise/Excercise and Target Reps headers.");setWorkouts(parsed)}catch(error){setMessage(error instanceof Error?`Could not read spreadsheet: ${error.message}`:"Could not read spreadsheet.")}finally{setParsing(false)}}

  function editWorkout(wi:number,name:string){setResult(null);setWorkouts(current=>current.map((w,i)=>i===wi?{...w,name}:w))}
  function removeWorkout(wi:number){setResult(null);setWorkouts(current=>current.filter((_,i)=>i!==wi))}
  function editExercise(wi:number,ei:number,field:"name"|"notes",value:string){setResult(null);setWorkouts(current=>current.map((w,i)=>i!==wi?w:{...w,exercises:w.exercises.map((e,j)=>j===ei?{...e,[field]:field==="notes"?(value||null):value}:e)}))}
  function removeExercise(wi:number,ei:number){setResult(null);setWorkouts(current=>current.map((w,i)=>i!==wi?w:{...w,exercises:w.exercises.filter((_,j)=>j!==ei)}))}
  function editTarget(wi:number,ei:number,si:number,value:string){setResult(null);setWorkouts(current=>current.map((w,i)=>i!==wi?w:{...w,exercises:w.exercises.map((e,j)=>j!==ei?e:{...e,sets:e.sets.map((s,k)=>k===si?{...s,targetReps:value||null}:s)})}))}
  function removeTarget(wi:number,ei:number,si:number){setResult(null);setWorkouts(current=>current.map((w,i)=>i!==wi?w:{...w,exercises:w.exercises.map((e,j)=>j!==ei?e:{...e,sets:e.sets.filter((_,k)=>k!==si)})}))}
  function addTarget(wi:number,ei:number){setResult(null);setWorkouts(current=>current.map((w,i)=>i!==wi?w:{...w,exercises:w.exercises.map((e,j)=>j!==ei?e:{...e,sets:[...e.sets,{targetReps:null}]})}))}

  function validationIssue(){if(!athleteId)return"Choose an athlete first.";if(!workouts.length)return"Choose a workout spreadsheet first.";for(const w of workouts){if(!w.name.trim())return"Every workout needs a name.";if(!w.exercises.length)return`${w.name} has no exercises.`;for(const e of w.exercises){if(!e.name.trim())return`${w.name} has an exercise with no name.`;if(!e.sets.length)return`${e.name} has no prescribed sets.`;}}return""}
  async function commitImport(){if(importing)return;const issue=validationIssue();if(issue){setMessage(`PHATBOT input check: ${issue}`);return}setImporting(true);setMessage("");setResult(null);try{const s=createSupabaseBrowserClient();const payload=workouts.map(w=>({name:w.name.trim(),exercises:w.exercises.map(e=>({name:e.name.trim(),notes:e.notes,targets:e.sets.map(x=>x.targetReps??"")}))}));const{data,error}=await s.rpc("import_coach_workout_templates",{p_athlete_user_id:athleteId,p_workouts:payload});if(error)throw error;const r=data as{created?:number;updated?:number};setResult({created:r.created??0,updated:r.updated??0})}catch(e){setMessage(e instanceof Error?`Import failed: ${e.message}`:"Import failed. No workout templates were created.")}finally{setImporting(false)}}

  const exerciseCount=workouts.reduce((n,w)=>n+w.exercises.length,0),setCount=workouts.reduce((n,w)=>n+w.exercises.reduce((m,e)=>m+e.sets.length,0),0),warningCount=workouts.reduce((n,w)=>n+w.warnings.length,0),athlete=athletes.find(a=>a.id===athleteId);
  if(loading)return <main className="mx-auto min-h-screen max-w-4xl px-4 py-10 sm:px-6"><p className="text-zinc-300">Beep boop... preparing template scanner.</p></main>;

  return <main className="mx-auto flex min-h-screen max-w-4xl flex-col gap-6 px-4 py-8 sm:px-6 sm:py-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.25em] text-zinc-400">PHATBOT Coach</p><h1 className="mt-2 text-3xl font-bold">Import Workout Template</h1><p className="mt-2 max-w-2xl text-zinc-400">Upload the spreadsheet you already use, review the compact preview, and expand only the workouts or exercises you want to edit.</p></div><div className="flex flex-wrap gap-2"><Link href="/coach/import/history" className="whitespace-nowrap rounded-lg border border-zinc-700 px-4 py-2 text-center text-sm font-semibold">Import History</Link><Link href="/coach" className="whitespace-nowrap rounded-lg border border-zinc-700 px-4 py-2 text-center text-sm font-semibold">Back to Coach</Link></div></header>

    <section className="rounded-2xl border border-zinc-800 p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="text-sm font-semibold">1. Choose athlete</span><select value={athleteId} onChange={e=>{setAthleteId(e.target.value);setResult(null)}} className="mt-2 w-full rounded-lg border border-zinc-700 bg-black px-3 py-3"><option value="">Select linked athlete</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="block"><span className="text-sm font-semibold">2. Choose XLSX file</span><input type="file" accept=".xlsx" onChange={e=>parseFile(e.target.files?.[0]??null)} className="mt-2 block w-full rounded-lg border border-zinc-700 px-3 py-3 text-sm"/></label></div><p className="mt-4 text-xs leading-5 text-zinc-500">Nothing is written until you press Import Workouts. Existing active workouts with the same name are updated to match this edited template instead of duplicated.</p></section>

    {message&&<section className="rounded-xl border border-zinc-700 p-4 text-sm text-zinc-200">{message}</section>}{parsing&&<p className="text-zinc-300">Beep boop... inspecting workbook structure.</p>}
    {result&&<section className="rounded-2xl border border-[#ff0032]/40 bg-[#ff0032]/5 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#ff0032]">Template Import Complete</p><h2 className="mt-2 text-2xl font-bold">Workouts transmitted to {athlete?.name??"the athlete"}.</h2><p className="mt-2 text-zinc-300">{result.created} created · {result.updated} updated.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/coach" className="rounded-lg bg-[#ff0032] px-4 py-2 text-sm font-bold text-white">Back to Coach</Link><button onClick={()=>{setWorkouts([]);setFileName("");setResult(null);setMessage("")}} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm font-semibold">Import Another File</button></div></section>}

    {workouts.length>0&&<><section className="grid gap-3 sm:grid-cols-4"><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">File</p><p className="mt-1 break-words font-semibold">{fileName}</p></div><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">Workouts</p><p className="mt-1 text-2xl font-black">{workouts.length}</p></div><div className="rounded-xl border border-zinc-800 p-4"><p className="text-xs text-zinc-500">Exercises / Sets</p><p className="mt-1 text-2xl font-black">{exerciseCount} / {setCount}</p></div><div className={`rounded-xl border p-4 ${warningCount?"border-zinc-500":"border-zinc-800"}`}><p className="text-xs text-zinc-500">Source Warnings</p><p className="mt-1 text-2xl font-black">{warningCount}</p></div></section>

    <section className="flex flex-col gap-3">{workouts.map((workout,wi)=>{const workoutSetCount=workout.exercises.reduce((n,e)=>n+e.sets.length,0);return <details key={`${workout.sheetName}-${wi}`} className="group rounded-2xl border border-zinc-800 bg-zinc-950/20"><summary className="cursor-pointer list-none p-4 sm:p-5"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-lg font-bold">{workout.name||"Untitled workout"}</p><p className="mt-1 text-sm text-zinc-500">{workout.exercises.length} exercises · {workoutSetCount} sets{workout.warnings.length?` · ${workout.warnings.length} warning${workout.warnings.length===1?"":"s"}`:""}</p></div><span className="shrink-0 text-sm font-semibold text-zinc-400 group-open:hidden">Edit ↓</span><span className="hidden shrink-0 text-sm font-semibold text-zinc-400 group-open:inline">Close ↑</span></div></summary><div className="border-t border-zinc-800 p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs text-zinc-500">Workout name<input value={workout.name} onChange={e=>editWorkout(wi,e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-lg font-bold"/></label><button onClick={()=>removeWorkout(wi)} className="self-end rounded-lg border border-zinc-800 px-3 py-2 text-sm text-zinc-400 hover:text-red-300">Remove workout</button></div><p className="mt-2 text-xs font-bold uppercase tracking-[.18em] text-zinc-600">Source tab: {workout.sheetName}</p>{workout.warnings.length>0&&<div className="mt-4 rounded-lg border border-zinc-700 p-3"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Source warnings</p>{workout.warnings.map((w,i)=><p key={i} className="mt-1 text-sm text-zinc-300">• {w}</p>)}</div>}
      <div className="mt-5 flex flex-col gap-2">{workout.exercises.map((exercise,ei)=><details key={`${exercise.name}-${ei}`} className="group rounded-xl bg-zinc-950"><summary className="cursor-pointer list-none p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{exercise.name||"Untitled exercise"}</p><p className="mt-1 text-xs text-zinc-600">{exercise.sets.length} prescribed set{exercise.sets.length===1?"":"s"}{exercise.notes?" · notes":""}</p></div><span className="text-xs text-zinc-500 group-open:hidden">Edit ↓</span><span className="hidden text-xs text-zinc-500 group-open:inline">Close ↑</span></div></summary><div className="border-t border-zinc-900 p-4"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs text-zinc-500">Exercise<input value={exercise.name} onChange={e=>editExercise(wi,ei,"name",e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-800 bg-black px-3 py-2 font-semibold"/></label><label className="text-xs text-zinc-500">Notes<input value={exercise.notes??""} onChange={e=>editExercise(wi,ei,"notes",e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-800 bg-black px-3 py-2 text-sm"/></label><button onClick={()=>removeExercise(wi,ei)} className="self-end rounded-lg border border-zinc-800 px-3 py-2 text-xs text-zinc-500 hover:text-red-300">Remove</button></div><div className="mt-3 flex flex-col gap-2">{exercise.sets.map((set,si)=><div key={si} className="grid grid-cols-[1fr_auto] gap-2"><label className="text-[11px] text-zinc-600">Set {si+1} target<input value={set.targetReps??""} onChange={e=>editTarget(wi,ei,si,e.target.value)} placeholder="e.g. 8-10, 15+, AMRAP" className="mt-1 w-full rounded border border-zinc-800 bg-black px-3 py-2 text-sm"/></label><button onClick={()=>removeTarget(wi,ei,si)} className="self-end rounded border border-zinc-800 px-2 py-2 text-xs text-zinc-600 hover:text-red-300">×</button></div>)}</div><button onClick={()=>addTarget(wi,ei)} className="mt-3 text-xs font-semibold underline">+ Add prescribed set</button></div></details>)}</div></div></details>})}</section>

    {!result&&<section className="sticky bottom-3 z-10 rounded-2xl border border-zinc-600 bg-black/95 p-5 shadow-2xl backdrop-blur sm:p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-400">Import checkpoint</p><h2 className="mt-2 text-xl font-bold">Preview ready for {athlete?.name??"the selected athlete"}.</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Review the compact summaries above. Expand only anything you want to change, then import.</p><button disabled={importing||Boolean(validationIssue())} onClick={commitImport} className="mt-4 w-full rounded-lg bg-[#ff0032] px-5 py-3 font-bold text-white disabled:cursor-not-allowed disabled:bg-zinc-800 disabled:text-zinc-500 sm:w-auto">{importing?"PHATBOT Importing...":"Import Workouts"}</button>{validationIssue()&&<p className="mt-2 text-xs text-zinc-500">{validationIssue()}</p>}</section>}</>}
  </main>
}
