"use client";

import { FormEvent, useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

export default function AcceptAthleteInvitePage(){
 const [password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState("Checking invitation..."),[ready,setReady]=useState(false),[saving,setSaving]=useState(false);
 useEffect(()=>{const supabase=createSupabaseBrowserClient();async function load(){const{data:{session}}=await supabase.auth.getSession();if(session){setReady(true);setMessage("Invitation accepted. Create your PHATBOT password to finish setup.");return;}setMessage("Open this page from the PHATBOT invitation email. If the link has expired, ask your coach to send a new invitation.");}load();},[]);
 async function submit(e:FormEvent){e.preventDefault();if(password.length<6){setMessage("Use a password with at least 6 characters.");return;}if(password!==confirm){setMessage("Passwords do not match.");return;}setSaving(true);const supabase=createSupabaseBrowserClient();const{error}=await supabase.auth.updateUser({password});if(error){setMessage(error.message);setSaving(false);return;}try{await supabase.rpc("claim_my_athlete_invitations");}catch{}window.location.href="/";}
 return <main className="mx-auto flex min-h-screen max-w-md flex-col justify-center px-6 py-12"><p className="phat-accent text-sm font-semibold uppercase tracking-[.25em]">PHATBOT Athlete</p><h1 className="mt-2 text-4xl font-bold">Activate your account</h1><p className="mt-3 text-zinc-400">Your coach may already be building your workouts. Finish setup and they will be waiting for you.</p><p className="mt-6 rounded-xl border border-zinc-800 p-4 text-sm">{message}</p>{ready&&<form onSubmit={submit} className="mt-6 flex flex-col gap-4"><label className="text-sm font-semibold">Create password<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-black px-4 py-3" required/></label><label className="text-sm font-semibold">Confirm password<input type="password" minLength={6} value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-700 bg-black px-4 py-3" required/></label><button disabled={saving} className="phat-accent-bg rounded-lg px-5 py-3 font-bold disabled:opacity-50">{saving?"Activating...":"Enter PHATBOT"}</button></form>}</main>;
}
